// DO NOT EDIT! This file was auto-generated by crates/build/re_types_builder/src/codegen/cpp/mod.rs
// Based on "crates/store/re_sdk_types/definitions/rerun/components/bits_per_sample.fbs".

#pragma once

#include "../datatypes/uint32.hpp"
#include "../result.hpp"

#include <cstdint>
#include <memory>

namespace rerun::components {
    /// **Component**: Bit depth of audio samples.
    ///
    /// Matches Symphonia's `CodecParameters.bits_per_sample`.
    ///
    /// Common values: 8, 16 (CD quality), 24 (professional), 32.
    struct BitsPerSample {
        rerun::datatypes::UInt32 bits;

      public:
        BitsPerSample() = default;

        BitsPerSample(rerun::datatypes::UInt32 bits_) : bits(bits_) {}

        BitsPerSample& operator=(rerun::datatypes::UInt32 bits_) {
            bits = bits_;
            return *this;
        }

        BitsPerSample(uint32_t value_) : bits(value_) {}

        BitsPerSample& operator=(uint32_t value_) {
            bits = value_;
            return *this;
        }

        /// Cast to the underlying UInt32 datatype
        operator rerun::datatypes::UInt32() const {
            return bits;
        }
    };
} // namespace rerun::components

namespace rerun {
    static_assert(sizeof(rerun::datatypes::UInt32) == sizeof(components::BitsPerSample));

    /// \private
    template <>
    struct Loggable<components::BitsPerSample> {
        static constexpr std::string_view ComponentType = "rerun.components.BitsPerSample";

        /// Returns the arrow data type this type corresponds to.
        static const std::shared_ptr<arrow::DataType>& arrow_datatype() {
            return Loggable<rerun::datatypes::UInt32>::arrow_datatype();
        }

        /// Serializes an array of `rerun::components::BitsPerSample` into an arrow array.
        static Result<std::shared_ptr<arrow::Array>> to_arrow(
            const components::BitsPerSample* instances, size_t num_instances
        ) {
            if (num_instances == 0) {
                return Loggable<rerun::datatypes::UInt32>::to_arrow(nullptr, 0);
            } else if (instances == nullptr) {
                return rerun::Error(
                    ErrorCode::UnexpectedNullArgument,
                    "Passed array instances is null when num_elements> 0."
                );
            } else {
                return Loggable<rerun::datatypes::UInt32>::to_arrow(
                    &instances->bits,
                    num_instances
                );
            }
        }
    };
} // namespace rerun
