// DO NOT EDIT! This file was auto-generated by crates/build/re_types_builder/src/codegen/cpp/mod.rs
// Based on "crates/store/re_sdk_types/definitions/rerun/components/channel_layout.fbs".

#pragma once

#include "../datatypes/uint32.hpp"
#include "../result.hpp"

#include <cstdint>
#include <memory>

namespace rerun::components {
    /// **Component**: Audio channel layout as a bitmask.
    ///
    /// Matches Symphonia's `Channels` type. Bits follow the WAVEFORMATEXTENSIBLE
    /// standard (channels 0-17) plus Symphonia extensions (18+).
    ///
    /// Common layouts:
    /// * `0x1` = Mono (Front Center)
    /// * `0x3` = Stereo (Front Left + Front Right)
    /// * `0x3F` = 5.1 Surround
    /// * `0xFF` = 7.1 Surround
    ///
    /// Use `count_ones()` to get the number of channels from the bitmask.
    struct ChannelLayout {
        /// Bitmask of active channels.
        rerun::datatypes::UInt32 bits;

      public:
        ChannelLayout() = default;

        ChannelLayout(rerun::datatypes::UInt32 bits_) : bits(bits_) {}

        ChannelLayout& operator=(rerun::datatypes::UInt32 bits_) {
            bits = bits_;
            return *this;
        }

        ChannelLayout(uint32_t value_) : bits(value_) {}

        ChannelLayout& operator=(uint32_t value_) {
            bits = value_;
            return *this;
        }

        /// Cast to the underlying UInt32 datatype
        operator rerun::datatypes::UInt32() const {
            return bits;
        }
    };
} // namespace rerun::components

namespace rerun {
    static_assert(sizeof(rerun::datatypes::UInt32) == sizeof(components::ChannelLayout));

    /// \private
    template <>
    struct Loggable<components::ChannelLayout> {
        static constexpr std::string_view ComponentType = "rerun.components.ChannelLayout";

        /// Returns the arrow data type this type corresponds to.
        static const std::shared_ptr<arrow::DataType>& arrow_datatype() {
            return Loggable<rerun::datatypes::UInt32>::arrow_datatype();
        }

        /// Serializes an array of `rerun::components::ChannelLayout` into an arrow array.
        static Result<std::shared_ptr<arrow::Array>> to_arrow(
            const components::ChannelLayout* instances, size_t num_instances
        ) {
            if (num_instances == 0) {
                return Loggable<rerun::datatypes::UInt32>::to_arrow(nullptr, 0);
            } else if (instances == nullptr) {
                return rerun::Error(
                    ErrorCode::UnexpectedNullArgument,
                    "Passed array instances is null when num_elements> 0."
                );
            } else {
                return Loggable<rerun::datatypes::UInt32>::to_arrow(
                    &instances->bits,
                    num_instances
                );
            }
        }
    };
} // namespace rerun
