// DO NOT EDIT! This file was auto-generated by crates/build/re_types_builder/src/codegen/cpp/mod.rs
// Based on "crates/store/re_sdk_types/definitions/rerun/components/sample_format.fbs".

#pragma once

#include "../datatypes/sample_format.hpp"
#include "../result.hpp"

#include <cstdint>
#include <memory>

namespace rerun::components {
    /// **Component**: Audio sample format.
    ///
    /// Wraps Symphonia's `SampleFormat`. Describes how decoded audio samples
    /// are represented in memory.
    ///
    /// Only needed for raw PCM data where the format cannot be inferred
    /// from the container.
    struct SampleFormat {
        rerun::datatypes::SampleFormat format;

      public:
        SampleFormat() = default;

        SampleFormat(rerun::datatypes::SampleFormat format_) : format(format_) {}

        SampleFormat& operator=(rerun::datatypes::SampleFormat format_) {
            format = format_;
            return *this;
        }

        /// Cast to the underlying SampleFormat datatype
        operator rerun::datatypes::SampleFormat() const {
            return format;
        }
    };
} // namespace rerun::components

namespace rerun {
    static_assert(sizeof(rerun::datatypes::SampleFormat) == sizeof(components::SampleFormat));

    /// \private
    template <>
    struct Loggable<components::SampleFormat> {
        static constexpr std::string_view ComponentType = "rerun.components.SampleFormat";

        /// Returns the arrow data type this type corresponds to.
        static const std::shared_ptr<arrow::DataType>& arrow_datatype() {
            return Loggable<rerun::datatypes::SampleFormat>::arrow_datatype();
        }

        /// Serializes an array of `rerun::components::SampleFormat` into an arrow array.
        static Result<std::shared_ptr<arrow::Array>> to_arrow(
            const components::SampleFormat* instances, size_t num_instances
        ) {
            if (num_instances == 0) {
                return Loggable<rerun::datatypes::SampleFormat>::to_arrow(nullptr, 0);
            } else if (instances == nullptr) {
                return rerun::Error(
                    ErrorCode::UnexpectedNullArgument,
                    "Passed array instances is null when num_elements> 0."
                );
            } else {
                return Loggable<rerun::datatypes::SampleFormat>::to_arrow(
                    &instances->format,
                    num_instances
                );
            }
        }
    };
} // namespace rerun
