// DO NOT EDIT! This file was auto-generated by crates/build/re_types_builder/src/codegen/cpp/mod.rs
// Based on "crates/store/re_sdk_types/definitions/rerun/components/sample_rate.fbs".

#pragma once

#include "../datatypes/uint32.hpp"
#include "../result.hpp"

#include <cstdint>
#include <memory>

namespace rerun::components {
    /// **Component**: Audio sample rate in Hz.
    ///
    /// Common values: 44100 (CD), 48000 (professional), 96000 (high-res),
    /// 192000 (ultra high-res), 250000-500000 (ultrasonic/bat detection).
    struct SampleRate {
        rerun::datatypes::UInt32 hz;

      public:
        SampleRate() = default;

        SampleRate(rerun::datatypes::UInt32 hz_) : hz(hz_) {}

        SampleRate& operator=(rerun::datatypes::UInt32 hz_) {
            hz = hz_;
            return *this;
        }

        SampleRate(uint32_t value_) : hz(value_) {}

        SampleRate& operator=(uint32_t value_) {
            hz = value_;
            return *this;
        }

        /// Cast to the underlying UInt32 datatype
        operator rerun::datatypes::UInt32() const {
            return hz;
        }
    };
} // namespace rerun::components

namespace rerun {
    static_assert(sizeof(rerun::datatypes::UInt32) == sizeof(components::SampleRate));

    /// \private
    template <>
    struct Loggable<components::SampleRate> {
        static constexpr std::string_view ComponentType = "rerun.components.SampleRate";

        /// Returns the arrow data type this type corresponds to.
        static const std::shared_ptr<arrow::DataType>& arrow_datatype() {
            return Loggable<rerun::datatypes::UInt32>::arrow_datatype();
        }

        /// Serializes an array of `rerun::components::SampleRate` into an arrow array.
        static Result<std::shared_ptr<arrow::Array>> to_arrow(
            const components::SampleRate* instances, size_t num_instances
        ) {
            if (num_instances == 0) {
                return Loggable<rerun::datatypes::UInt32>::to_arrow(nullptr, 0);
            } else if (instances == nullptr) {
                return rerun::Error(
                    ErrorCode::UnexpectedNullArgument,
                    "Passed array instances is null when num_elements> 0."
                );
            } else {
                return Loggable<rerun::datatypes::UInt32>::to_arrow(&instances->hz, num_instances);
            }
        }
    };
} // namespace rerun
