// DO NOT EDIT! This file was auto-generated by crates/build/re_types_builder/src/codegen/cpp/mod.rs
// Based on "crates/store/re_sdk_types/definitions/rerun/components/sample_offset.fbs".

#pragma once

#include "../datatypes/uint64.hpp"
#include "../result.hpp"

#include <cstdint>
#include <memory>

namespace rerun::components {
    /// **Component**: Sample offset into an audio stream.
    ///
    /// Used by `AudioSampleReference` to point into an `AssetAudio`,
    /// and by `AudioDetection` to define detection boundaries.
    struct SampleOffset {
        rerun::datatypes::UInt64 offset;

      public:
        SampleOffset() = default;

        SampleOffset(rerun::datatypes::UInt64 offset_) : offset(offset_) {}

        SampleOffset& operator=(rerun::datatypes::UInt64 offset_) {
            offset = offset_;
            return *this;
        }

        SampleOffset(uint64_t value_) : offset(value_) {}

        SampleOffset& operator=(uint64_t value_) {
            offset = value_;
            return *this;
        }

        /// Cast to the underlying UInt64 datatype
        operator rerun::datatypes::UInt64() const {
            return offset;
        }
    };
} // namespace rerun::components

namespace rerun {
    static_assert(sizeof(rerun::datatypes::UInt64) == sizeof(components::SampleOffset));

    /// \private
    template <>
    struct Loggable<components::SampleOffset> {
        static constexpr std::string_view ComponentType = "rerun.components.SampleOffset";

        /// Returns the arrow data type this type corresponds to.
        static const std::shared_ptr<arrow::DataType>& arrow_datatype() {
            return Loggable<rerun::datatypes::UInt64>::arrow_datatype();
        }

        /// Serializes an array of `rerun::components::SampleOffset` into an arrow array.
        static Result<std::shared_ptr<arrow::Array>> to_arrow(
            const components::SampleOffset* instances, size_t num_instances
        ) {
            if (num_instances == 0) {
                return Loggable<rerun::datatypes::UInt64>::to_arrow(nullptr, 0);
            } else if (instances == nullptr) {
                return rerun::Error(
                    ErrorCode::UnexpectedNullArgument,
                    "Passed array instances is null when num_elements> 0."
                );
            } else {
                return Loggable<rerun::datatypes::UInt64>::to_arrow(
                    &instances->offset,
                    num_instances
                );
            }
        }
    };
} // namespace rerun
