// DO NOT EDIT! This file was auto-generated by crates/build/re_types_builder/src/codegen/cpp/mod.rs
// Based on "crates/store/re_sdk_types/definitions/rerun/components/sample_count.fbs".

#pragma once

#include "../datatypes/uint64.hpp"
#include "../result.hpp"

#include <cstdint>
#include <memory>

namespace rerun::components {
    /// **Component**: Number of audio samples (duration in samples).
    ///
    /// To convert to seconds: `duration_sec = sample_count / sample_rate`
    struct SampleCount {
        rerun::datatypes::UInt64 count;

      public:
        SampleCount() = default;

        SampleCount(rerun::datatypes::UInt64 count_) : count(count_) {}

        SampleCount& operator=(rerun::datatypes::UInt64 count_) {
            count = count_;
            return *this;
        }

        SampleCount(uint64_t value_) : count(value_) {}

        SampleCount& operator=(uint64_t value_) {
            count = value_;
            return *this;
        }

        /// Cast to the underlying UInt64 datatype
        operator rerun::datatypes::UInt64() const {
            return count;
        }
    };
} // namespace rerun::components

namespace rerun {
    static_assert(sizeof(rerun::datatypes::UInt64) == sizeof(components::SampleCount));

    /// \private
    template <>
    struct Loggable<components::SampleCount> {
        static constexpr std::string_view ComponentType = "rerun.components.SampleCount";

        /// Returns the arrow data type this type corresponds to.
        static const std::shared_ptr<arrow::DataType>& arrow_datatype() {
            return Loggable<rerun::datatypes::UInt64>::arrow_datatype();
        }

        /// Serializes an array of `rerun::components::SampleCount` into an arrow array.
        static Result<std::shared_ptr<arrow::Array>> to_arrow(
            const components::SampleCount* instances, size_t num_instances
        ) {
            if (num_instances == 0) {
                return Loggable<rerun::datatypes::UInt64>::to_arrow(nullptr, 0);
            } else if (instances == nullptr) {
                return rerun::Error(
                    ErrorCode::UnexpectedNullArgument,
                    "Passed array instances is null when num_elements> 0."
                );
            } else {
                return Loggable<rerun::datatypes::UInt64>::to_arrow(
                    &instances->count,
                    num_instances
                );
            }
        }
    };
} // namespace rerun
