// DO NOT EDIT! This file was auto-generated by crates/build/re_types_builder/src/codegen/rust/api.rs
// Based on "crates/store/re_sdk_types/definitions/rerun/datatypes/sample_format.fbs".

#![allow(unused_braces)]
#![allow(unused_imports)]
#![allow(unused_parens)]
#![allow(clippy::allow_attributes)]
#![allow(clippy::clone_on_copy)]
#![allow(clippy::cloned_instead_of_copied)]
#![allow(clippy::map_flatten)]
#![allow(clippy::needless_question_mark)]
#![allow(clippy::new_without_default)]
#![allow(clippy::redundant_closure)]
#![allow(clippy::too_many_arguments)]
#![allow(clippy::too_many_lines)]
#![allow(clippy::wildcard_imports)]
#![allow(non_camel_case_types)]

use ::re_types_core::SerializationResult;
use ::re_types_core::try_serialize_field;
use ::re_types_core::{ComponentBatch as _, SerializedComponentBatch};
use ::re_types_core::{ComponentDescriptor, ComponentType};
use ::re_types_core::{DeserializationError, DeserializationResult};

/// **Datatype**: Audio sample format.
///
/// Matches Symphonia's `SampleFormat` enum. Describes how decoded audio
/// samples are represented in memory.
#[derive(Clone, Copy, Debug, Hash, PartialEq, Eq)]
#[repr(u8)]
pub enum SampleFormat {
    /// Unsigned 8-bit integer.
    U8 = 1,

    /// Unsigned 16-bit integer.
    U16 = 2,

    /// Unsigned 24-bit integer (stored in 32 bits).
    U24 = 3,

    /// Unsigned 32-bit integer.
    U32 = 4,

    /// Signed 8-bit integer.
    S8 = 5,

    /// Signed 16-bit integer (CD quality).
    S16 = 6,

    /// Signed 24-bit integer (professional audio).
    S24 = 7,

    /// Signed 32-bit integer.
    S32 = 8,

    /// 32-bit IEEE-754 floating point.
    F32 = 9,

    /// 64-bit IEEE-754 floating point.
    F64 = 10,
}

::re_types_core::macros::impl_into_cow!(SampleFormat);

impl ::re_types_core::Loggable for SampleFormat {
    #[inline]
    fn arrow_datatype() -> arrow::datatypes::DataType {
        use arrow::datatypes::*;
        DataType::UInt8
    }

    fn to_arrow_opt<'a>(
        data: impl IntoIterator<Item = Option<impl Into<::std::borrow::Cow<'a, Self>>>>,
    ) -> SerializationResult<arrow::array::ArrayRef>
    where
        Self: Clone + 'a,
    {
        #![allow(clippy::manual_is_variant_and)]
        use ::re_types_core::{Loggable as _, ResultExt as _, arrow_helpers::as_array_ref};
        use arrow::{array::*, buffer::*, datatypes::*};
        Ok({
            let (somes, data0): (Vec<_>, Vec<_>) = data
                .into_iter()
                .map(|datum| {
                    let datum: Option<::std::borrow::Cow<'a, Self>> = datum.map(Into::into);
                    let datum = datum.map(|datum| *datum as u8);
                    (datum.is_some(), datum)
                })
                .unzip();
            let data0_validity: Option<arrow::buffer::NullBuffer> = {
                let any_nones = somes.iter().any(|some| !*some);
                any_nones.then(|| somes.into())
            };
            as_array_ref(PrimitiveArray::<UInt8Type>::new(
                ScalarBuffer::from(
                    data0
                        .into_iter()
                        .map(|v| v.unwrap_or_default())
                        .collect::<Vec<_>>(),
                ),
                data0_validity,
            ))
        })
    }

    fn from_arrow_opt(
        arrow_data: &dyn arrow::array::Array,
    ) -> DeserializationResult<Vec<Option<Self>>>
    where
        Self: Sized,
    {
        use ::re_types_core::{Loggable as _, ResultExt as _, arrow_zip_validity::ZipValidity};
        use arrow::{array::*, buffer::*, datatypes::*};
        Ok(arrow_data
            .as_any()
            .downcast_ref::<UInt8Array>()
            .ok_or_else(|| {
                let expected = Self::arrow_datatype();
                let actual = arrow_data.data_type().clone();
                DeserializationError::datatype_mismatch(expected, actual)
            })
            .with_context("rerun.datatypes.SampleFormat#enum")?
            .into_iter()
            .map(|typ| match typ {
                Some(1) => Ok(Some(Self::U8)),
                Some(2) => Ok(Some(Self::U16)),
                Some(3) => Ok(Some(Self::U24)),
                Some(4) => Ok(Some(Self::U32)),
                Some(5) => Ok(Some(Self::S8)),
                Some(6) => Ok(Some(Self::S16)),
                Some(7) => Ok(Some(Self::S24)),
                Some(8) => Ok(Some(Self::S32)),
                Some(9) => Ok(Some(Self::F32)),
                Some(10) => Ok(Some(Self::F64)),
                None => Ok(None),
                Some(invalid) => Err(DeserializationError::missing_union_arm(
                    Self::arrow_datatype(),
                    "<invalid>",
                    invalid as _,
                )),
            })
            .collect::<DeserializationResult<Vec<Option<_>>>>()
            .with_context("rerun.datatypes.SampleFormat")?)
    }
}

impl std::fmt::Display for SampleFormat {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            Self::U8 => write!(f, "U8"),
            Self::U16 => write!(f, "U16"),
            Self::U24 => write!(f, "U24"),
            Self::U32 => write!(f, "U32"),
            Self::S8 => write!(f, "S8"),
            Self::S16 => write!(f, "S16"),
            Self::S24 => write!(f, "S24"),
            Self::S32 => write!(f, "S32"),
            Self::F32 => write!(f, "F32"),
            Self::F64 => write!(f, "F64"),
        }
    }
}

impl ::re_types_core::reflection::Enum for SampleFormat {
    #[inline]
    fn variants() -> &'static [Self] {
        &[
            Self::U8,
            Self::U16,
            Self::U24,
            Self::U32,
            Self::S8,
            Self::S16,
            Self::S24,
            Self::S32,
            Self::F32,
            Self::F64,
        ]
    }

    #[inline]
    fn docstring_md(self) -> &'static str {
        match self {
            Self::U8 => "Unsigned 8-bit integer.",
            Self::U16 => "Unsigned 16-bit integer.",
            Self::U24 => "Unsigned 24-bit integer (stored in 32 bits).",
            Self::U32 => "Unsigned 32-bit integer.",
            Self::S8 => "Signed 8-bit integer.",
            Self::S16 => "Signed 16-bit integer (CD quality).",
            Self::S24 => "Signed 24-bit integer (professional audio).",
            Self::S32 => "Signed 32-bit integer.",
            Self::F32 => "32-bit IEEE-754 floating point.",
            Self::F64 => "64-bit IEEE-754 floating point.",
        }
    }
}

impl ::re_byte_size::SizeBytes for SampleFormat {
    #[inline]
    fn heap_size_bytes(&self) -> u64 {
        0
    }

    #[inline]
    fn is_pod() -> bool {
        true
    }
}
