// DO NOT EDIT! This file was auto-generated by crates/build/re_types_builder/src/codegen/rust/api.rs
// Based on "crates/store/re_sdk_types/definitions/rerun/components/channel_layout.fbs".

#![allow(unused_braces)]
#![allow(unused_imports)]
#![allow(unused_parens)]
#![allow(clippy::allow_attributes)]
#![allow(clippy::clone_on_copy)]
#![allow(clippy::cloned_instead_of_copied)]
#![allow(clippy::map_flatten)]
#![allow(clippy::needless_question_mark)]
#![allow(clippy::new_without_default)]
#![allow(clippy::redundant_closure)]
#![allow(clippy::too_many_arguments)]
#![allow(clippy::too_many_lines)]
#![allow(clippy::wildcard_imports)]

use ::re_types_core::SerializationResult;
use ::re_types_core::try_serialize_field;
use ::re_types_core::{ComponentBatch as _, SerializedComponentBatch};
use ::re_types_core::{ComponentDescriptor, ComponentType};
use ::re_types_core::{DeserializationError, DeserializationResult};

/// **Component**: Audio channel layout as a bitmask.
///
/// Matches Symphonia's `Channels` type. Bits follow the WAVEFORMATEXTENSIBLE
/// standard (channels 0-17) plus Symphonia extensions (18+).
///
/// Common layouts:
/// * `0x1` = Mono (Front Center)
/// * `0x3` = Stereo (Front Left + Front Right)
/// * `0x3F` = 5.1 Surround
/// * `0xFF` = 7.1 Surround
///
/// Use `count_ones()` to get the number of channels from the bitmask.
#[derive(Clone, Debug, Copy, PartialEq, Eq)]
#[repr(transparent)]
pub struct ChannelLayout(
    /// Bitmask of active channels.
    pub crate::datatypes::UInt32,
);

impl ::re_types_core::WrapperComponent for ChannelLayout {
    type Datatype = crate::datatypes::UInt32;

    #[inline]
    fn name() -> ComponentType {
        "rerun.components.ChannelLayout".into()
    }

    #[inline]
    fn into_inner(self) -> Self::Datatype {
        self.0
    }
}

::re_types_core::macros::impl_into_cow!(ChannelLayout);

impl<T: Into<crate::datatypes::UInt32>> From<T> for ChannelLayout {
    fn from(v: T) -> Self {
        Self(v.into())
    }
}

impl std::borrow::Borrow<crate::datatypes::UInt32> for ChannelLayout {
    #[inline]
    fn borrow(&self) -> &crate::datatypes::UInt32 {
        &self.0
    }
}

impl std::ops::Deref for ChannelLayout {
    type Target = crate::datatypes::UInt32;

    #[inline]
    fn deref(&self) -> &crate::datatypes::UInt32 {
        &self.0
    }
}

impl std::ops::DerefMut for ChannelLayout {
    #[inline]
    fn deref_mut(&mut self) -> &mut crate::datatypes::UInt32 {
        &mut self.0
    }
}

impl ::re_byte_size::SizeBytes for ChannelLayout {
    #[inline]
    fn heap_size_bytes(&self) -> u64 {
        self.0.heap_size_bytes()
    }

    #[inline]
    fn is_pod() -> bool {
        <crate::datatypes::UInt32>::is_pod()
    }
}
