// DO NOT EDIT! This file was auto-generated by crates/build/re_types_builder/src/codegen/rust/api.rs
// Based on "crates/store/re_sdk_types/definitions/rerun/components/sample_count.fbs".

#![allow(unused_braces)]
#![allow(unused_imports)]
#![allow(unused_parens)]
#![allow(clippy::allow_attributes)]
#![allow(clippy::clone_on_copy)]
#![allow(clippy::cloned_instead_of_copied)]
#![allow(clippy::map_flatten)]
#![allow(clippy::needless_question_mark)]
#![allow(clippy::new_without_default)]
#![allow(clippy::redundant_closure)]
#![allow(clippy::too_many_arguments)]
#![allow(clippy::too_many_lines)]
#![allow(clippy::wildcard_imports)]

use ::re_types_core::SerializationResult;
use ::re_types_core::try_serialize_field;
use ::re_types_core::{ComponentBatch as _, SerializedComponentBatch};
use ::re_types_core::{ComponentDescriptor, ComponentType};
use ::re_types_core::{DeserializationError, DeserializationResult};

/// **Component**: Number of audio samples (duration in samples).
///
/// To convert to seconds: `duration_sec = sample_count / sample_rate`
#[derive(Clone, Debug, Copy, PartialEq, Eq, PartialOrd, Ord)]
#[repr(transparent)]
pub struct SampleCount(pub crate::datatypes::UInt64);

impl ::re_types_core::WrapperComponent for SampleCount {
    type Datatype = crate::datatypes::UInt64;

    #[inline]
    fn name() -> ComponentType {
        "rerun.components.SampleCount".into()
    }

    #[inline]
    fn into_inner(self) -> Self::Datatype {
        self.0
    }
}

::re_types_core::macros::impl_into_cow!(SampleCount);

impl<T: Into<crate::datatypes::UInt64>> From<T> for SampleCount {
    fn from(v: T) -> Self {
        Self(v.into())
    }
}

impl std::borrow::Borrow<crate::datatypes::UInt64> for SampleCount {
    #[inline]
    fn borrow(&self) -> &crate::datatypes::UInt64 {
        &self.0
    }
}

impl std::ops::Deref for SampleCount {
    type Target = crate::datatypes::UInt64;

    #[inline]
    fn deref(&self) -> &crate::datatypes::UInt64 {
        &self.0
    }
}

impl std::ops::DerefMut for SampleCount {
    #[inline]
    fn deref_mut(&mut self) -> &mut crate::datatypes::UInt64 {
        &mut self.0
    }
}

impl ::re_byte_size::SizeBytes for SampleCount {
    #[inline]
    fn heap_size_bytes(&self) -> u64 {
        self.0.heap_size_bytes()
    }

    #[inline]
    fn is_pod() -> bool {
        <crate::datatypes::UInt64>::is_pod()
    }
}
