// DO NOT EDIT! This file was auto-generated by crates/build/re_types_builder/src/codegen/cpp/mod.rs
// Based on "crates/store/re_sdk_types/definitions/rerun/archetypes/asset_audio.fbs".

#include "asset_audio.hpp"

#include "../collection_adapter_builtins.hpp"

namespace rerun::archetypes {
    AssetAudio AssetAudio::clear_fields() {
        auto archetype = AssetAudio();
        archetype.blob =
            ComponentBatch::empty<rerun::components::Blob>(Descriptor_blob).value_or_throw();
        archetype.media_type =
            ComponentBatch::empty<rerun::components::MediaType>(Descriptor_media_type)
                .value_or_throw();
        archetype.sample_rate =
            ComponentBatch::empty<rerun::components::SampleRate>(Descriptor_sample_rate)
                .value_or_throw();
        archetype.channel_layout =
            ComponentBatch::empty<rerun::components::ChannelLayout>(Descriptor_channel_layout)
                .value_or_throw();
        archetype.bits_per_sample =
            ComponentBatch::empty<rerun::components::BitsPerSample>(Descriptor_bits_per_sample)
                .value_or_throw();
        archetype.sample_format =
            ComponentBatch::empty<rerun::components::SampleFormat>(Descriptor_sample_format)
                .value_or_throw();
        return archetype;
    }

    Collection<ComponentColumn> AssetAudio::columns(const Collection<uint32_t>& lengths_) {
        std::vector<ComponentColumn> columns;
        columns.reserve(6);
        if (blob.has_value()) {
            columns.push_back(blob.value().partitioned(lengths_).value_or_throw());
        }
        if (media_type.has_value()) {
            columns.push_back(media_type.value().partitioned(lengths_).value_or_throw());
        }
        if (sample_rate.has_value()) {
            columns.push_back(sample_rate.value().partitioned(lengths_).value_or_throw());
        }
        if (channel_layout.has_value()) {
            columns.push_back(channel_layout.value().partitioned(lengths_).value_or_throw());
        }
        if (bits_per_sample.has_value()) {
            columns.push_back(bits_per_sample.value().partitioned(lengths_).value_or_throw());
        }
        if (sample_format.has_value()) {
            columns.push_back(sample_format.value().partitioned(lengths_).value_or_throw());
        }
        return columns;
    }

    Collection<ComponentColumn> AssetAudio::columns() {
        if (blob.has_value()) {
            return columns(std::vector<uint32_t>(blob.value().length(), 1));
        }
        if (media_type.has_value()) {
            return columns(std::vector<uint32_t>(media_type.value().length(), 1));
        }
        if (sample_rate.has_value()) {
            return columns(std::vector<uint32_t>(sample_rate.value().length(), 1));
        }
        if (channel_layout.has_value()) {
            return columns(std::vector<uint32_t>(channel_layout.value().length(), 1));
        }
        if (bits_per_sample.has_value()) {
            return columns(std::vector<uint32_t>(bits_per_sample.value().length(), 1));
        }
        if (sample_format.has_value()) {
            return columns(std::vector<uint32_t>(sample_format.value().length(), 1));
        }
        return Collection<ComponentColumn>();
    }
} // namespace rerun::archetypes

namespace rerun {

    Result<Collection<ComponentBatch>> AsComponents<archetypes::AssetAudio>::as_batches(
        const archetypes::AssetAudio& archetype
    ) {
        using namespace archetypes;
        std::vector<ComponentBatch> cells;
        cells.reserve(6);

        if (archetype.blob.has_value()) {
            cells.push_back(archetype.blob.value());
        }
        if (archetype.media_type.has_value()) {
            cells.push_back(archetype.media_type.value());
        }
        if (archetype.sample_rate.has_value()) {
            cells.push_back(archetype.sample_rate.value());
        }
        if (archetype.channel_layout.has_value()) {
            cells.push_back(archetype.channel_layout.value());
        }
        if (archetype.bits_per_sample.has_value()) {
            cells.push_back(archetype.bits_per_sample.value());
        }
        if (archetype.sample_format.has_value()) {
            cells.push_back(archetype.sample_format.value());
        }

        return rerun::take_ownership(std::move(cells));
    }
} // namespace rerun
