// DO NOT EDIT! This file was auto-generated by crates/build/re_types_builder/src/codegen/cpp/mod.rs
// Based on "crates/store/re_sdk_types/definitions/rerun/archetypes/asset_audio.fbs".

#pragma once

#include "../collection.hpp"
#include "../component_batch.hpp"
#include "../component_column.hpp"
#include "../components/bits_per_sample.hpp"
#include "../components/blob.hpp"
#include "../components/channel_layout.hpp"
#include "../components/media_type.hpp"
#include "../components/sample_format.hpp"
#include "../components/sample_rate.hpp"
#include "../result.hpp"

#include <cstdint>
#include <optional>
#include <utility>
#include <vector>

namespace rerun::archetypes {
    /// **Archetype**: An audio asset containing encoded or raw audio data.
    ///
    /// Store this once (typically as static/timeless data), then use
    /// `AudioSampleReference` to reference specific positions on your timeline.
    ///
    /// Similar to how `AssetVideo` + `VideoFrameReference` work for video.
    ///
    /// ## Supported Formats
    ///
    /// - **FLAC**: Lossless, recommended for archival and analysis
    /// - **WAV**: Uncompressed PCM in a container
    /// - **MP3**: Lossy, widely compatible
    /// - **OGG**: Container for Opus or Vorbis codecs
    ///
    /// Codec detection is automatic via Symphonia. The optional metadata fields
    /// (`sample_rate`, `channel_layout`, etc.) are hints that can speed up
    /// initialization but are not required.
    ///
    /// ⚠ **This type is _unstable_ and may change significantly in a way that the data won't be backwards compatible.**
    ///
    struct AssetAudio {
        /// The audio data bytes.
        ///
        /// For encoded formats (FLAC, MP3, etc.), this is the raw file/stream bytes.
        /// For raw PCM, this is the sample bytes (use `sample_format` to specify encoding).
        std::optional<ComponentBatch> blob;

        /// The Media Type of the audio container.
        ///
        /// Supported values:
        /// * `audio/flac`
        /// * `audio/wav`
        /// * `audio/mpeg` (MP3)
        /// * `audio/ogg` (Opus or Vorbis)
        ///
        /// If omitted, the viewer will try to guess from the data blob.
        std::optional<ComponentBatch> media_type;

        /// Sample rate in Hz (e.g., 48000).
        ///
        /// Matches Symphonia's `SignalSpec.rate`. For encoded formats this can be
        /// read from headers, but providing it enables faster initialization.
        std::optional<ComponentBatch> sample_rate;

        /// Channel layout as a bitmask.
        ///
        /// Matches Symphonia's `Channels`. Common values:
        /// * `0x3` = Stereo
        /// * `0x3F` = 5.1 Surround
        std::optional<ComponentBatch> channel_layout;

        /// Bit depth of audio samples (8, 16, 24, or 32).
        ///
        /// Matches Symphonia's `CodecParameters.bits_per_sample`.
        std::optional<ComponentBatch> bits_per_sample;

        /// Sample format for raw PCM data.
        ///
        /// Only needed when logging raw PCM bytes without a container.
        /// For encoded formats (FLAC, MP3, etc.), this is ignored.
        std::optional<ComponentBatch> sample_format;

      public:
        /// The name of the archetype as used in `ComponentDescriptor`s.
        static constexpr const char ArchetypeName[] = "rerun.archetypes.AssetAudio";

        /// `ComponentDescriptor` for the `blob` field.
        static constexpr auto Descriptor_blob = ComponentDescriptor(
            ArchetypeName, "AssetAudio:blob", Loggable<rerun::components::Blob>::ComponentType
        );
        /// `ComponentDescriptor` for the `media_type` field.
        static constexpr auto Descriptor_media_type = ComponentDescriptor(
            ArchetypeName, "AssetAudio:media_type",
            Loggable<rerun::components::MediaType>::ComponentType
        );
        /// `ComponentDescriptor` for the `sample_rate` field.
        static constexpr auto Descriptor_sample_rate = ComponentDescriptor(
            ArchetypeName, "AssetAudio:sample_rate",
            Loggable<rerun::components::SampleRate>::ComponentType
        );
        /// `ComponentDescriptor` for the `channel_layout` field.
        static constexpr auto Descriptor_channel_layout = ComponentDescriptor(
            ArchetypeName, "AssetAudio:channel_layout",
            Loggable<rerun::components::ChannelLayout>::ComponentType
        );
        /// `ComponentDescriptor` for the `bits_per_sample` field.
        static constexpr auto Descriptor_bits_per_sample = ComponentDescriptor(
            ArchetypeName, "AssetAudio:bits_per_sample",
            Loggable<rerun::components::BitsPerSample>::ComponentType
        );
        /// `ComponentDescriptor` for the `sample_format` field.
        static constexpr auto Descriptor_sample_format = ComponentDescriptor(
            ArchetypeName, "AssetAudio:sample_format",
            Loggable<rerun::components::SampleFormat>::ComponentType
        );

      public:
        AssetAudio() = default;
        AssetAudio(AssetAudio&& other) = default;
        AssetAudio(const AssetAudio& other) = default;
        AssetAudio& operator=(const AssetAudio& other) = default;
        AssetAudio& operator=(AssetAudio&& other) = default;

        explicit AssetAudio(rerun::components::Blob _blob)
            : blob(ComponentBatch::from_loggable(std::move(_blob), Descriptor_blob).value_or_throw()
              ) {}

        /// Update only some specific fields of a `AssetAudio`.
        static AssetAudio update_fields() {
            return AssetAudio();
        }

        /// Clear all the fields of a `AssetAudio`.
        static AssetAudio clear_fields();

        /// The audio data bytes.
        ///
        /// For encoded formats (FLAC, MP3, etc.), this is the raw file/stream bytes.
        /// For raw PCM, this is the sample bytes (use `sample_format` to specify encoding).
        AssetAudio with_blob(const rerun::components::Blob& _blob) && {
            blob = ComponentBatch::from_loggable(_blob, Descriptor_blob).value_or_throw();
            return std::move(*this);
        }

        /// This method makes it possible to pack multiple `blob` in a single component batch.
        ///
        /// This only makes sense when used in conjunction with `columns`. `with_blob` should
        /// be used when logging a single row's worth of data.
        AssetAudio with_many_blob(const Collection<rerun::components::Blob>& _blob) && {
            blob = ComponentBatch::from_loggable(_blob, Descriptor_blob).value_or_throw();
            return std::move(*this);
        }

        /// The Media Type of the audio container.
        ///
        /// Supported values:
        /// * `audio/flac`
        /// * `audio/wav`
        /// * `audio/mpeg` (MP3)
        /// * `audio/ogg` (Opus or Vorbis)
        ///
        /// If omitted, the viewer will try to guess from the data blob.
        AssetAudio with_media_type(const rerun::components::MediaType& _media_type) && {
            media_type =
                ComponentBatch::from_loggable(_media_type, Descriptor_media_type).value_or_throw();
            return std::move(*this);
        }

        /// This method makes it possible to pack multiple `media_type` in a single component batch.
        ///
        /// This only makes sense when used in conjunction with `columns`. `with_media_type` should
        /// be used when logging a single row's worth of data.
        AssetAudio with_many_media_type(const Collection<rerun::components::MediaType>& _media_type
        ) && {
            media_type =
                ComponentBatch::from_loggable(_media_type, Descriptor_media_type).value_or_throw();
            return std::move(*this);
        }

        /// Sample rate in Hz (e.g., 48000).
        ///
        /// Matches Symphonia's `SignalSpec.rate`. For encoded formats this can be
        /// read from headers, but providing it enables faster initialization.
        AssetAudio with_sample_rate(const rerun::components::SampleRate& _sample_rate) && {
            sample_rate = ComponentBatch::from_loggable(_sample_rate, Descriptor_sample_rate)
                              .value_or_throw();
            return std::move(*this);
        }

        /// This method makes it possible to pack multiple `sample_rate` in a single component batch.
        ///
        /// This only makes sense when used in conjunction with `columns`. `with_sample_rate` should
        /// be used when logging a single row's worth of data.
        AssetAudio with_many_sample_rate(
            const Collection<rerun::components::SampleRate>& _sample_rate
        ) && {
            sample_rate = ComponentBatch::from_loggable(_sample_rate, Descriptor_sample_rate)
                              .value_or_throw();
            return std::move(*this);
        }

        /// Channel layout as a bitmask.
        ///
        /// Matches Symphonia's `Channels`. Common values:
        /// * `0x3` = Stereo
        /// * `0x3F` = 5.1 Surround
        AssetAudio with_channel_layout(const rerun::components::ChannelLayout& _channel_layout) && {
            channel_layout =
                ComponentBatch::from_loggable(_channel_layout, Descriptor_channel_layout)
                    .value_or_throw();
            return std::move(*this);
        }

        /// This method makes it possible to pack multiple `channel_layout` in a single component batch.
        ///
        /// This only makes sense when used in conjunction with `columns`. `with_channel_layout` should
        /// be used when logging a single row's worth of data.
        AssetAudio with_many_channel_layout(
            const Collection<rerun::components::ChannelLayout>& _channel_layout
        ) && {
            channel_layout =
                ComponentBatch::from_loggable(_channel_layout, Descriptor_channel_layout)
                    .value_or_throw();
            return std::move(*this);
        }

        /// Bit depth of audio samples (8, 16, 24, or 32).
        ///
        /// Matches Symphonia's `CodecParameters.bits_per_sample`.
        AssetAudio with_bits_per_sample(const rerun::components::BitsPerSample& _bits_per_sample
        ) && {
            bits_per_sample =
                ComponentBatch::from_loggable(_bits_per_sample, Descriptor_bits_per_sample)
                    .value_or_throw();
            return std::move(*this);
        }

        /// This method makes it possible to pack multiple `bits_per_sample` in a single component batch.
        ///
        /// This only makes sense when used in conjunction with `columns`. `with_bits_per_sample` should
        /// be used when logging a single row's worth of data.
        AssetAudio with_many_bits_per_sample(
            const Collection<rerun::components::BitsPerSample>& _bits_per_sample
        ) && {
            bits_per_sample =
                ComponentBatch::from_loggable(_bits_per_sample, Descriptor_bits_per_sample)
                    .value_or_throw();
            return std::move(*this);
        }

        /// Sample format for raw PCM data.
        ///
        /// Only needed when logging raw PCM bytes without a container.
        /// For encoded formats (FLAC, MP3, etc.), this is ignored.
        AssetAudio with_sample_format(const rerun::components::SampleFormat& _sample_format) && {
            sample_format = ComponentBatch::from_loggable(_sample_format, Descriptor_sample_format)
                                .value_or_throw();
            return std::move(*this);
        }

        /// This method makes it possible to pack multiple `sample_format` in a single component batch.
        ///
        /// This only makes sense when used in conjunction with `columns`. `with_sample_format` should
        /// be used when logging a single row's worth of data.
        AssetAudio with_many_sample_format(
            const Collection<rerun::components::SampleFormat>& _sample_format
        ) && {
            sample_format = ComponentBatch::from_loggable(_sample_format, Descriptor_sample_format)
                                .value_or_throw();
            return std::move(*this);
        }

        /// Partitions the component data into multiple sub-batches.
        ///
        /// Specifically, this transforms the existing `ComponentBatch` data into `ComponentColumn`s
        /// instead, via `ComponentBatch::partitioned`.
        ///
        /// This makes it possible to use `RecordingStream::send_columns` to send columnar data directly into Rerun.
        ///
        /// The specified `lengths` must sum to the total length of the component batch.
        Collection<ComponentColumn> columns(const Collection<uint32_t>& lengths_);

        /// Partitions the component data into unit-length sub-batches.
        ///
        /// This is semantically similar to calling `columns` with `std::vector<uint32_t>(n, 1)`,
        /// where `n` is automatically guessed.
        Collection<ComponentColumn> columns();
    };

} // namespace rerun::archetypes

namespace rerun {
    /// \private
    template <typename T>
    struct AsComponents;

    /// \private
    template <>
    struct AsComponents<archetypes::AssetAudio> {
        /// Serialize all set component batches.
        static Result<Collection<ComponentBatch>> as_batches(const archetypes::AssetAudio& archetype
        );
    };
} // namespace rerun
