// DO NOT EDIT! This file was auto-generated by crates/build/re_types_builder/src/codegen/cpp/mod.rs
// Based on "crates/store/re_sdk_types/definitions/rerun/archetypes/audio_sample_reference.fbs".

#include "audio_sample_reference.hpp"

#include "../collection_adapter_builtins.hpp"

namespace rerun::archetypes {
    AudioSampleReference AudioSampleReference::clear_fields() {
        auto archetype = AudioSampleReference();
        archetype.sample_offset =
            ComponentBatch::empty<rerun::components::SampleOffset>(Descriptor_sample_offset)
                .value_or_throw();
        archetype.duration_samples =
            ComponentBatch::empty<rerun::components::SampleCount>(Descriptor_duration_samples)
                .value_or_throw();
        return archetype;
    }

    Collection<ComponentColumn> AudioSampleReference::columns(const Collection<uint32_t>& lengths_
    ) {
        std::vector<ComponentColumn> columns;
        columns.reserve(2);
        if (sample_offset.has_value()) {
            columns.push_back(sample_offset.value().partitioned(lengths_).value_or_throw());
        }
        if (duration_samples.has_value()) {
            columns.push_back(duration_samples.value().partitioned(lengths_).value_or_throw());
        }
        return columns;
    }

    Collection<ComponentColumn> AudioSampleReference::columns() {
        if (sample_offset.has_value()) {
            return columns(std::vector<uint32_t>(sample_offset.value().length(), 1));
        }
        if (duration_samples.has_value()) {
            return columns(std::vector<uint32_t>(duration_samples.value().length(), 1));
        }
        return Collection<ComponentColumn>();
    }
} // namespace rerun::archetypes

namespace rerun {

    Result<Collection<ComponentBatch>> AsComponents<archetypes::AudioSampleReference>::as_batches(
        const archetypes::AudioSampleReference& archetype
    ) {
        using namespace archetypes;
        std::vector<ComponentBatch> cells;
        cells.reserve(2);

        if (archetype.sample_offset.has_value()) {
            cells.push_back(archetype.sample_offset.value());
        }
        if (archetype.duration_samples.has_value()) {
            cells.push_back(archetype.duration_samples.value());
        }

        return rerun::take_ownership(std::move(cells));
    }
} // namespace rerun
