// DO NOT EDIT! This file was auto-generated by crates/build/re_types_builder/src/codegen/cpp/mod.rs
// Based on "crates/store/re_sdk_types/definitions/rerun/archetypes/audio_sample_reference.fbs".

#pragma once

#include "../collection.hpp"
#include "../component_batch.hpp"
#include "../component_column.hpp"
#include "../components/sample_count.hpp"
#include "../components/sample_offset.hpp"
#include "../result.hpp"

#include <cstdint>
#include <optional>
#include <utility>
#include <vector>

namespace rerun::archetypes {
    /// **Archetype**: Reference to a position within an `AssetAudio`.
    ///
    /// Used to place audio on the timeline and enable synchronized playback
    /// with other data streams (video, sensors, detections).
    ///
    /// Log these at timestamps where you want the audio to be "active" on the timeline.
    /// The viewer will decode and play from the specified sample offset.
    ///
    /// ⚠ **This type is _unstable_ and may change significantly in a way that the data won't be backwards compatible.**
    ///
    struct AudioSampleReference {
        /// Sample offset into the audio stream.
        ///
        /// The viewer will seek to this position when the timeline reaches
        /// this timestamp. For continuous playback, log references at regular
        /// intervals (e.g., every second).
        std::optional<ComponentBatch> sample_offset;

        /// Optional: Number of samples to play from this offset.
        ///
        /// If not specified, plays until the next reference or end of asset.
        std::optional<ComponentBatch> duration_samples;

      public:
        /// The name of the archetype as used in `ComponentDescriptor`s.
        static constexpr const char ArchetypeName[] = "rerun.archetypes.AudioSampleReference";

        /// `ComponentDescriptor` for the `sample_offset` field.
        static constexpr auto Descriptor_sample_offset = ComponentDescriptor(
            ArchetypeName, "AudioSampleReference:sample_offset",
            Loggable<rerun::components::SampleOffset>::ComponentType
        );
        /// `ComponentDescriptor` for the `duration_samples` field.
        static constexpr auto Descriptor_duration_samples = ComponentDescriptor(
            ArchetypeName, "AudioSampleReference:duration_samples",
            Loggable<rerun::components::SampleCount>::ComponentType
        );

      public:
        AudioSampleReference() = default;
        AudioSampleReference(AudioSampleReference&& other) = default;
        AudioSampleReference(const AudioSampleReference& other) = default;
        AudioSampleReference& operator=(const AudioSampleReference& other) = default;
        AudioSampleReference& operator=(AudioSampleReference&& other) = default;

        explicit AudioSampleReference(rerun::components::SampleOffset _sample_offset)
            : sample_offset(
                  ComponentBatch::from_loggable(std::move(_sample_offset), Descriptor_sample_offset)
                      .value_or_throw()
              ) {}

        /// Update only some specific fields of a `AudioSampleReference`.
        static AudioSampleReference update_fields() {
            return AudioSampleReference();
        }

        /// Clear all the fields of a `AudioSampleReference`.
        static AudioSampleReference clear_fields();

        /// Sample offset into the audio stream.
        ///
        /// The viewer will seek to this position when the timeline reaches
        /// this timestamp. For continuous playback, log references at regular
        /// intervals (e.g., every second).
        AudioSampleReference with_sample_offset(
            const rerun::components::SampleOffset& _sample_offset
        ) && {
            sample_offset = ComponentBatch::from_loggable(_sample_offset, Descriptor_sample_offset)
                                .value_or_throw();
            return std::move(*this);
        }

        /// This method makes it possible to pack multiple `sample_offset` in a single component batch.
        ///
        /// This only makes sense when used in conjunction with `columns`. `with_sample_offset` should
        /// be used when logging a single row's worth of data.
        AudioSampleReference with_many_sample_offset(
            const Collection<rerun::components::SampleOffset>& _sample_offset
        ) && {
            sample_offset = ComponentBatch::from_loggable(_sample_offset, Descriptor_sample_offset)
                                .value_or_throw();
            return std::move(*this);
        }

        /// Optional: Number of samples to play from this offset.
        ///
        /// If not specified, plays until the next reference or end of asset.
        AudioSampleReference with_duration_samples(
            const rerun::components::SampleCount& _duration_samples
        ) && {
            duration_samples =
                ComponentBatch::from_loggable(_duration_samples, Descriptor_duration_samples)
                    .value_or_throw();
            return std::move(*this);
        }

        /// This method makes it possible to pack multiple `duration_samples` in a single component batch.
        ///
        /// This only makes sense when used in conjunction with `columns`. `with_duration_samples` should
        /// be used when logging a single row's worth of data.
        AudioSampleReference with_many_duration_samples(
            const Collection<rerun::components::SampleCount>& _duration_samples
        ) && {
            duration_samples =
                ComponentBatch::from_loggable(_duration_samples, Descriptor_duration_samples)
                    .value_or_throw();
            return std::move(*this);
        }

        /// Partitions the component data into multiple sub-batches.
        ///
        /// Specifically, this transforms the existing `ComponentBatch` data into `ComponentColumn`s
        /// instead, via `ComponentBatch::partitioned`.
        ///
        /// This makes it possible to use `RecordingStream::send_columns` to send columnar data directly into Rerun.
        ///
        /// The specified `lengths` must sum to the total length of the component batch.
        Collection<ComponentColumn> columns(const Collection<uint32_t>& lengths_);

        /// Partitions the component data into unit-length sub-batches.
        ///
        /// This is semantically similar to calling `columns` with `std::vector<uint32_t>(n, 1)`,
        /// where `n` is automatically guessed.
        Collection<ComponentColumn> columns();
    };

} // namespace rerun::archetypes

namespace rerun {
    /// \private
    template <typename T>
    struct AsComponents;

    /// \private
    template <>
    struct AsComponents<archetypes::AudioSampleReference> {
        /// Serialize all set component batches.
        static Result<Collection<ComponentBatch>> as_batches(
            const archetypes::AudioSampleReference& archetype
        );
    };
} // namespace rerun
