# DO NOT EDIT! This file was auto-generated by crates/build/re_types_builder/src/codegen/python/mod.rs
# Based on "crates/store/re_sdk_types/definitions/rerun/components/bits_per_sample.fbs".

# You can extend this class by creating a "BitsPerSampleExt" class in "bits_per_sample_ext.py".

from __future__ import annotations

from .. import datatypes
from .._baseclasses import (
    ComponentBatchMixin,
    ComponentMixin,
)

__all__ = ["BitsPerSample", "BitsPerSampleBatch"]


class BitsPerSample(datatypes.UInt32, ComponentMixin):
    """
    **Component**: Bit depth of audio samples.

    Matches Symphonia's `CodecParameters.bits_per_sample`.

    Common values: 8, 16 (CD quality), 24 (professional), 32.
    """

    _BATCH_TYPE = None
    # You can define your own __init__ function as a member of BitsPerSampleExt in bits_per_sample_ext.py

    # Note: there are no fields here because BitsPerSample delegates to datatypes.UInt32


class BitsPerSampleBatch(datatypes.UInt32Batch, ComponentBatchMixin):
    _COMPONENT_TYPE: str = "rerun.components.BitsPerSample"


# This is patched in late to avoid circular dependencies.
BitsPerSample._BATCH_TYPE = BitsPerSampleBatch  # type: ignore[assignment]
