# DO NOT EDIT! This file was auto-generated by crates/build/re_types_builder/src/codegen/python/mod.rs
# Based on "crates/store/re_sdk_types/definitions/rerun/components/channel_layout.fbs".

# You can extend this class by creating a "ChannelLayoutExt" class in "channel_layout_ext.py".

from __future__ import annotations

from .. import datatypes
from .._baseclasses import (
    ComponentBatchMixin,
    ComponentMixin,
)

__all__ = ["ChannelLayout", "ChannelLayoutBatch"]


class ChannelLayout(datatypes.UInt32, ComponentMixin):
    """
    **Component**: Audio channel layout as a bitmask.

    Matches Symphonia's `Channels` type. Bits follow the WAVEFORMATEXTENSIBLE
    standard (channels 0-17) plus Symphonia extensions (18+).

    Common layouts:
    * `0x1` = Mono (Front Center)
    * `0x3` = Stereo (Front Left + Front Right)
    * `0x3F` = 5.1 Surround
    * `0xFF` = 7.1 Surround

    Use `count_ones()` to get the number of channels from the bitmask.
    """

    _BATCH_TYPE = None
    # You can define your own __init__ function as a member of ChannelLayoutExt in channel_layout_ext.py

    # Note: there are no fields here because ChannelLayout delegates to datatypes.UInt32


class ChannelLayoutBatch(datatypes.UInt32Batch, ComponentBatchMixin):
    _COMPONENT_TYPE: str = "rerun.components.ChannelLayout"


# This is patched in late to avoid circular dependencies.
ChannelLayout._BATCH_TYPE = ChannelLayoutBatch  # type: ignore[assignment]
