# DO NOT EDIT! This file was auto-generated by crates/build/re_types_builder/src/codegen/python/mod.rs
# Based on "crates/store/re_sdk_types/definitions/rerun/components/sample_rate.fbs".

# You can extend this class by creating a "SampleRateExt" class in "sample_rate_ext.py".

from __future__ import annotations

from .. import datatypes
from .._baseclasses import (
    ComponentBatchMixin,
    ComponentMixin,
)

__all__ = ["SampleRate", "SampleRateBatch"]


class SampleRate(datatypes.UInt32, ComponentMixin):
    """
    **Component**: Audio sample rate in Hz.

    Common values: 44100 (CD), 48000 (professional), 96000 (high-res),
    192000 (ultra high-res), 250000-500000 (ultrasonic/bat detection).
    """

    _BATCH_TYPE = None
    # You can define your own __init__ function as a member of SampleRateExt in sample_rate_ext.py

    # Note: there are no fields here because SampleRate delegates to datatypes.UInt32


class SampleRateBatch(datatypes.UInt32Batch, ComponentBatchMixin):
    _COMPONENT_TYPE: str = "rerun.components.SampleRate"


# This is patched in late to avoid circular dependencies.
SampleRate._BATCH_TYPE = SampleRateBatch  # type: ignore[assignment]
