# DO NOT EDIT! This file was auto-generated by crates/build/re_types_builder/src/codegen/python/mod.rs
# Based on "crates/store/re_sdk_types/definitions/rerun/components/sample_count.fbs".

# You can extend this class by creating a "SampleCountExt" class in "sample_count_ext.py".

from __future__ import annotations

from .. import datatypes
from .._baseclasses import (
    ComponentBatchMixin,
    ComponentMixin,
)

__all__ = ["SampleCount", "SampleCountBatch"]


class SampleCount(datatypes.UInt64, ComponentMixin):
    """
    **Component**: Number of audio samples (duration in samples).

    To convert to seconds: `duration_sec = sample_count / sample_rate`
    """

    _BATCH_TYPE = None
    # You can define your own __init__ function as a member of SampleCountExt in sample_count_ext.py

    # Note: there are no fields here because SampleCount delegates to datatypes.UInt64


class SampleCountBatch(datatypes.UInt64Batch, ComponentBatchMixin):
    _COMPONENT_TYPE: str = "rerun.components.SampleCount"


# This is patched in late to avoid circular dependencies.
SampleCount._BATCH_TYPE = SampleCountBatch  # type: ignore[assignment]
