# DO NOT EDIT! This file was auto-generated by crates/build/re_types_builder/src/codegen/python/mod.rs
# Based on "crates/store/re_sdk_types/definitions/rerun/components/sample_format.fbs".

# You can extend this class by creating a "SampleFormatExt" class in "sample_format_ext.py".

from __future__ import annotations

from .. import datatypes
from .._baseclasses import (
    ComponentBatchMixin,
    ComponentMixin,
)

__all__ = ["SampleFormat", "SampleFormatBatch"]


class SampleFormat(datatypes.SampleFormat, ComponentMixin):
    """
    **Component**: Audio sample format.

    Wraps Symphonia's `SampleFormat`. Describes how decoded audio samples
    are represented in memory.

    Only needed for raw PCM data where the format cannot be inferred
    from the container.
    """

    _BATCH_TYPE = None
    # You can define your own __init__ function as a member of SampleFormatExt in sample_format_ext.py

    # Note: there are no fields here because SampleFormat delegates to datatypes.SampleFormat


class SampleFormatBatch(datatypes.SampleFormatBatch, ComponentBatchMixin):
    _COMPONENT_TYPE: str = "rerun.components.SampleFormat"


# This is patched in late to avoid circular dependencies.
SampleFormat._BATCH_TYPE = SampleFormatBatch  # type: ignore[assignment]
