# DO NOT EDIT! This file was auto-generated by crates/build/re_types_builder/src/codegen/python/mod.rs
# Based on "crates/store/re_sdk_types/definitions/rerun/components/sample_offset.fbs".

# You can extend this class by creating a "SampleOffsetExt" class in "sample_offset_ext.py".

from __future__ import annotations

from .. import datatypes
from .._baseclasses import (
    ComponentBatchMixin,
    ComponentMixin,
)

__all__ = ["SampleOffset", "SampleOffsetBatch"]


class SampleOffset(datatypes.UInt64, ComponentMixin):
    """
    **Component**: Sample offset into an audio stream.

    Used by `AudioSampleReference` to point into an `AssetAudio`,
    and by `AudioDetection` to define detection boundaries.
    """

    _BATCH_TYPE = None
    # You can define your own __init__ function as a member of SampleOffsetExt in sample_offset_ext.py

    # Note: there are no fields here because SampleOffset delegates to datatypes.UInt64


class SampleOffsetBatch(datatypes.UInt64Batch, ComponentBatchMixin):
    _COMPONENT_TYPE: str = "rerun.components.SampleOffset"


# This is patched in late to avoid circular dependencies.
SampleOffset._BATCH_TYPE = SampleOffsetBatch  # type: ignore[assignment]
