# DO NOT EDIT! This file was auto-generated by crates/build/re_types_builder/src/codegen/python/mod.rs
# Based on "crates/store/re_sdk_types/definitions/rerun/datatypes/sample_format.fbs".

# You can extend this class by creating a "SampleFormatExt" class in "sample_format_ext.py".

from __future__ import annotations

from collections.abc import Sequence
from typing import Literal

import pyarrow as pa

from .._baseclasses import (
    BaseBatch,
)

__all__ = ["SampleFormat", "SampleFormatArrayLike", "SampleFormatBatch", "SampleFormatLike"]


from enum import Enum


class SampleFormat(Enum):
    """
    **Datatype**: Audio sample format.

    Matches Symphonia's `SampleFormat` enum. Describes how decoded audio
    samples are represented in memory.
    """

    U8 = 1
    """Unsigned 8-bit integer."""

    U16 = 2
    """Unsigned 16-bit integer."""

    U24 = 3
    """Unsigned 24-bit integer (stored in 32 bits)."""

    U32 = 4
    """Unsigned 32-bit integer."""

    S8 = 5
    """Signed 8-bit integer."""

    S16 = 6
    """Signed 16-bit integer (CD quality)."""

    S24 = 7
    """Signed 24-bit integer (professional audio)."""

    S32 = 8
    """Signed 32-bit integer."""

    F32 = 9
    """32-bit IEEE-754 floating point."""

    F64 = 10
    """64-bit IEEE-754 floating point."""

    @classmethod
    def auto(cls, val: str | int | SampleFormat) -> SampleFormat:
        """Best-effort converter, including a case-insensitive string matcher."""
        if isinstance(val, SampleFormat):
            return val
        if isinstance(val, int):
            return cls(val)
        try:
            return cls[val]
        except KeyError:
            val_lower = val.lower()
            for variant in cls:
                if variant.name.lower() == val_lower:
                    return variant
        raise ValueError(f"Cannot convert {val} to {cls.__name__}")

    def __str__(self) -> str:
        """Returns the variant name."""
        return self.name


SampleFormatLike = (
    SampleFormat
    | Literal[
        "F32",
        "F64",
        "S16",
        "S24",
        "S32",
        "S8",
        "U16",
        "U24",
        "U32",
        "U8",
        "f32",
        "f64",
        "s16",
        "s24",
        "s32",
        "s8",
        "u16",
        "u24",
        "u32",
        "u8",
    ]
    | int
)
"""A type alias for any SampleFormat-like object."""

SampleFormatArrayLike = (
    SampleFormat
    | Literal[
        "F32",
        "F64",
        "S16",
        "S24",
        "S32",
        "S8",
        "U16",
        "U24",
        "U32",
        "U8",
        "f32",
        "f64",
        "s16",
        "s24",
        "s32",
        "s8",
        "u16",
        "u24",
        "u32",
        "u8",
    ]
    | int
    | Sequence[SampleFormatLike]
)
"""A type alias for any SampleFormat-like array object."""


class SampleFormatBatch(BaseBatch[SampleFormatArrayLike]):
    _ARROW_DATATYPE = pa.uint8()

    @staticmethod
    def _native_to_pa_array(data: SampleFormatArrayLike, data_type: pa.DataType) -> pa.Array:
        if isinstance(data, (SampleFormat, int, str)):
            data = [data]

        pa_data = [SampleFormat.auto(v).value if v is not None else None for v in data]  # type: ignore[redundant-expr]

        return pa.array(pa_data, type=data_type)
