# DO NOT EDIT! This file was auto-generated by crates/build/re_types_builder/src/codegen/python/mod.rs
# Based on "crates/store/re_sdk_types/definitions/rerun/archetypes/asset_audio.fbs".

# You can extend this class by creating a "AssetAudioExt" class in "asset_audio_ext.py".

from __future__ import annotations

import numpy as np
import pyarrow as pa
from attrs import define, field

from .. import components, datatypes
from .._baseclasses import (
    Archetype,
    ComponentColumnList,
)
from ..error_utils import catch_and_log_exceptions
from .asset_audio_ext import AssetAudioExt

__all__ = ["AssetAudio"]


@define(str=False, repr=False, init=False)
class AssetAudio(AssetAudioExt, Archetype):
    """
    **Archetype**: An audio asset containing encoded or raw audio data.

    Store this once (typically as static/timeless data), then use
    `AudioSampleReference` to reference specific positions on your timeline.

    Similar to how `AssetVideo` + `VideoFrameReference` work for video.

    ## Supported Formats

    - **FLAC**: Lossless, recommended for archival and analysis
    - **WAV**: Uncompressed PCM in a container
    - **MP3**: Lossy, widely compatible
    - **OGG**: Container for Opus or Vorbis codecs

    Codec detection is automatic via Symphonia. The optional metadata fields
    (`sample_rate`, `channel_layout`, etc.) are hints that can speed up
    initialization but are not required.

    ⚠️ **This type is _unstable_ and may change significantly in a way that the data won't be backwards compatible.**

    Example
    -------
    ### Log an audio file:
    ```python
    import rerun as rr

    rr.init("rerun_example_asset_audio", spawn=True)

    # Log audio asset
    rr.log("/recording/audio", rr.AssetAudio(path="recording.flac"), static=True)
    ```

    """

    # __init__ can be found in asset_audio_ext.py

    def __attrs_clear__(self) -> None:
        """Convenience method for calling `__attrs_init__` with all `None`s."""
        self.__attrs_init__(
            blob=None,
            media_type=None,
            sample_rate=None,
            channel_layout=None,
            bits_per_sample=None,
            sample_format=None,
        )

    @classmethod
    def _clear(cls) -> AssetAudio:
        """Produce an empty AssetAudio, bypassing `__init__`."""
        inst = cls.__new__(cls)
        inst.__attrs_clear__()
        return inst

    @classmethod
    def from_fields(
        cls,
        *,
        clear_unset: bool = False,
        blob: datatypes.BlobLike | None = None,
        media_type: datatypes.Utf8Like | None = None,
        sample_rate: datatypes.UInt32Like | None = None,
        channel_layout: datatypes.UInt32Like | None = None,
        bits_per_sample: datatypes.UInt32Like | None = None,
        sample_format: datatypes.SampleFormatLike | None = None,
    ) -> AssetAudio:
        """
        Update only some specific fields of a `AssetAudio`.

        Parameters
        ----------
        clear_unset:
            If true, all unspecified fields will be explicitly cleared.
        blob:
            The audio data bytes.

            For encoded formats (FLAC, MP3, etc.), this is the raw file/stream bytes.
            For raw PCM, this is the sample bytes (use `sample_format` to specify encoding).
        media_type:
            The Media Type of the audio container.

            Supported values:
            * `audio/flac`
            * `audio/wav`
            * `audio/mpeg` (MP3)
            * `audio/ogg` (Opus or Vorbis)

            If omitted, the viewer will try to guess from the data blob.
        sample_rate:
            Sample rate in Hz (e.g., 48000).

            Matches Symphonia's `SignalSpec.rate`. For encoded formats this can be
            read from headers, but providing it enables faster initialization.
        channel_layout:
            Channel layout as a bitmask.

            Matches Symphonia's `Channels`. Common values:
            * `0x3` = Stereo
            * `0x3F` = 5.1 Surround
        bits_per_sample:
            Bit depth of audio samples (8, 16, 24, or 32).

            Matches Symphonia's `CodecParameters.bits_per_sample`.
        sample_format:
            Sample format for raw PCM data.

            Only needed when logging raw PCM bytes without a container.
            For encoded formats (FLAC, MP3, etc.), this is ignored.

        """

        inst = cls.__new__(cls)
        with catch_and_log_exceptions(context=cls.__name__):
            kwargs = {
                "blob": blob,
                "media_type": media_type,
                "sample_rate": sample_rate,
                "channel_layout": channel_layout,
                "bits_per_sample": bits_per_sample,
                "sample_format": sample_format,
            }

            if clear_unset:
                kwargs = {k: v if v is not None else [] for k, v in kwargs.items()}  # type: ignore[misc]

            inst.__attrs_init__(**kwargs)
            return inst

        inst.__attrs_clear__()
        return inst

    @classmethod
    def cleared(cls) -> AssetAudio:
        """Clear all the fields of a `AssetAudio`."""
        return cls.from_fields(clear_unset=True)

    @classmethod
    def columns(
        cls,
        *,
        blob: datatypes.BlobArrayLike | None = None,
        media_type: datatypes.Utf8ArrayLike | None = None,
        sample_rate: datatypes.UInt32ArrayLike | None = None,
        channel_layout: datatypes.UInt32ArrayLike | None = None,
        bits_per_sample: datatypes.UInt32ArrayLike | None = None,
        sample_format: datatypes.SampleFormatArrayLike | None = None,
    ) -> ComponentColumnList:
        """
        Construct a new column-oriented component bundle.

        This makes it possible to use `rr.send_columns` to send columnar data directly into Rerun.

        The returned columns will be partitioned into unit-length sub-batches by default.
        Use `ComponentColumnList.partition` to repartition the data as needed.

        Parameters
        ----------
        blob:
            The audio data bytes.

            For encoded formats (FLAC, MP3, etc.), this is the raw file/stream bytes.
            For raw PCM, this is the sample bytes (use `sample_format` to specify encoding).
        media_type:
            The Media Type of the audio container.

            Supported values:
            * `audio/flac`
            * `audio/wav`
            * `audio/mpeg` (MP3)
            * `audio/ogg` (Opus or Vorbis)

            If omitted, the viewer will try to guess from the data blob.
        sample_rate:
            Sample rate in Hz (e.g., 48000).

            Matches Symphonia's `SignalSpec.rate`. For encoded formats this can be
            read from headers, but providing it enables faster initialization.
        channel_layout:
            Channel layout as a bitmask.

            Matches Symphonia's `Channels`. Common values:
            * `0x3` = Stereo
            * `0x3F` = 5.1 Surround
        bits_per_sample:
            Bit depth of audio samples (8, 16, 24, or 32).

            Matches Symphonia's `CodecParameters.bits_per_sample`.
        sample_format:
            Sample format for raw PCM data.

            Only needed when logging raw PCM bytes without a container.
            For encoded formats (FLAC, MP3, etc.), this is ignored.

        """

        inst = cls.__new__(cls)
        with catch_and_log_exceptions(context=cls.__name__):
            inst.__attrs_init__(
                blob=blob,
                media_type=media_type,
                sample_rate=sample_rate,
                channel_layout=channel_layout,
                bits_per_sample=bits_per_sample,
                sample_format=sample_format,
            )

        batches = inst.as_component_batches()
        if len(batches) == 0:
            return ComponentColumnList([])

        kwargs = {
            "AssetAudio:blob": blob,
            "AssetAudio:media_type": media_type,
            "AssetAudio:sample_rate": sample_rate,
            "AssetAudio:channel_layout": channel_layout,
            "AssetAudio:bits_per_sample": bits_per_sample,
            "AssetAudio:sample_format": sample_format,
        }
        columns = []

        for batch in batches:
            arrow_array = batch.as_arrow_array()

            # For primitive arrays and fixed size list arrays, we infer partition size from the input shape.
            if pa.types.is_primitive(arrow_array.type) or pa.types.is_fixed_size_list(arrow_array.type):
                param = kwargs[batch.component_descriptor().component]  # type: ignore[index]
                shape = np.shape(param)  # type: ignore[arg-type]
                elem_flat_len = int(np.prod(shape[1:])) if len(shape) > 1 else 1  # type: ignore[redundant-expr,misc]

                if pa.types.is_fixed_size_list(arrow_array.type) and arrow_array.type.list_size == elem_flat_len:
                    # If the product of the last dimensions of the shape are equal to the size of the fixed size list array,
                    # we have `num_rows` single element batches (each element is a fixed sized list).
                    # (This should have been already validated by conversion to the arrow_array)
                    batch_length = 1
                else:
                    batch_length = shape[1] if len(shape) > 1 else 1  # type: ignore[redundant-expr,misc]

                num_rows = shape[0] if len(shape) >= 1 else 1  # type: ignore[redundant-expr,misc]
                sizes = batch_length * np.ones(num_rows)
            else:
                # For non-primitive types, default to partitioning each element separately.
                sizes = np.ones(len(arrow_array))

            columns.append(batch.partition(sizes))

        return ComponentColumnList(columns)

    blob: components.BlobBatch | None = field(
        metadata={"component": True},
        default=None,
        converter=components.BlobBatch._converter,  # type: ignore[misc]
    )
    # The audio data bytes.
    #
    # For encoded formats (FLAC, MP3, etc.), this is the raw file/stream bytes.
    # For raw PCM, this is the sample bytes (use `sample_format` to specify encoding).
    #
    # (Docstring intentionally commented out to hide this field from the docs)

    media_type: components.MediaTypeBatch | None = field(
        metadata={"component": True},
        default=None,
        converter=components.MediaTypeBatch._converter,  # type: ignore[misc]
    )
    # The Media Type of the audio container.
    #
    # Supported values:
    # * `audio/flac`
    # * `audio/wav`
    # * `audio/mpeg` (MP3)
    # * `audio/ogg` (Opus or Vorbis)
    #
    # If omitted, the viewer will try to guess from the data blob.
    #
    # (Docstring intentionally commented out to hide this field from the docs)

    sample_rate: components.SampleRateBatch | None = field(
        metadata={"component": True},
        default=None,
        converter=components.SampleRateBatch._converter,  # type: ignore[misc]
    )
    # Sample rate in Hz (e.g., 48000).
    #
    # Matches Symphonia's `SignalSpec.rate`. For encoded formats this can be
    # read from headers, but providing it enables faster initialization.
    #
    # (Docstring intentionally commented out to hide this field from the docs)

    channel_layout: components.ChannelLayoutBatch | None = field(
        metadata={"component": True},
        default=None,
        converter=components.ChannelLayoutBatch._converter,  # type: ignore[misc]
    )
    # Channel layout as a bitmask.
    #
    # Matches Symphonia's `Channels`. Common values:
    # * `0x3` = Stereo
    # * `0x3F` = 5.1 Surround
    #
    # (Docstring intentionally commented out to hide this field from the docs)

    bits_per_sample: components.BitsPerSampleBatch | None = field(
        metadata={"component": True},
        default=None,
        converter=components.BitsPerSampleBatch._converter,  # type: ignore[misc]
    )
    # Bit depth of audio samples (8, 16, 24, or 32).
    #
    # Matches Symphonia's `CodecParameters.bits_per_sample`.
    #
    # (Docstring intentionally commented out to hide this field from the docs)

    sample_format: components.SampleFormatBatch | None = field(
        metadata={"component": True},
        default=None,
        converter=components.SampleFormatBatch._converter,  # type: ignore[misc]
    )
    # Sample format for raw PCM data.
    #
    # Only needed when logging raw PCM bytes without a container.
    # For encoded formats (FLAC, MP3, etc.), this is ignored.
    #
    # (Docstring intentionally commented out to hide this field from the docs)

    __str__ = Archetype.__str__
    __repr__ = Archetype.__repr__  # type: ignore[assignment]
