# DO NOT EDIT! This file was auto-generated by crates/build/re_types_builder/src/codegen/python/mod.rs
# Based on "crates/store/re_sdk_types/definitions/rerun/archetypes/audio_sample_reference.fbs".

# You can extend this class by creating a "AudioSampleReferenceExt" class in "audio_sample_reference_ext.py".

from __future__ import annotations

from typing import Any

import numpy as np
import pyarrow as pa
from attrs import define, field

from .. import components, datatypes
from .._baseclasses import (
    Archetype,
    ComponentColumnList,
)
from ..error_utils import catch_and_log_exceptions

__all__ = ["AudioSampleReference"]


@define(str=False, repr=False, init=False)
class AudioSampleReference(Archetype):
    """
    **Archetype**: Reference to a position within an `AssetAudio`.

    Used to place audio on the timeline and enable synchronized playback
    with other data streams (video, sensors, detections).

    Log these at timestamps where you want the audio to be "active" on the timeline.
    The viewer will decode and play from the specified sample offset.

    ⚠️ **This type is _unstable_ and may change significantly in a way that the data won't be backwards compatible.**

    Example
    -------
    ### Reference audio frames on timeline:
    ```python
    import rerun as rr

    rr.init("rerun_example_audio_sample_reference", spawn=True)

    # Log audio asset first
    rr.log("/recording/audio", rr.AssetAudio(path="recording.flac"), static=True)

    # Log timeline references
    sample_rate = 48000
    for t in range(60):  # 60 seconds
        rr.set_time_seconds("audio_time", float(t))
        rr.log("/recording/audio", rr.AudioSampleReference(sample_offset=t * sample_rate))
    ```

    """

    def __init__(
        self: Any, sample_offset: datatypes.UInt64Like, *, duration_samples: datatypes.UInt64Like | None = None
    ) -> None:
        """
        Create a new instance of the AudioSampleReference archetype.

        Parameters
        ----------
        sample_offset:
            Sample offset into the audio stream.

            The viewer will seek to this position when the timeline reaches
            this timestamp. For continuous playback, log references at regular
            intervals (e.g., every second).
        duration_samples:
            Optional: Number of samples to play from this offset.

            If not specified, plays until the next reference or end of asset.

        """

        # You can define your own __init__ function as a member of AudioSampleReferenceExt in audio_sample_reference_ext.py
        with catch_and_log_exceptions(context=self.__class__.__name__):
            self.__attrs_init__(sample_offset=sample_offset, duration_samples=duration_samples)
            return
        self.__attrs_clear__()

    def __attrs_clear__(self) -> None:
        """Convenience method for calling `__attrs_init__` with all `None`s."""
        self.__attrs_init__(
            sample_offset=None,
            duration_samples=None,
        )

    @classmethod
    def _clear(cls) -> AudioSampleReference:
        """Produce an empty AudioSampleReference, bypassing `__init__`."""
        inst = cls.__new__(cls)
        inst.__attrs_clear__()
        return inst

    @classmethod
    def from_fields(
        cls,
        *,
        clear_unset: bool = False,
        sample_offset: datatypes.UInt64Like | None = None,
        duration_samples: datatypes.UInt64Like | None = None,
    ) -> AudioSampleReference:
        """
        Update only some specific fields of a `AudioSampleReference`.

        Parameters
        ----------
        clear_unset:
            If true, all unspecified fields will be explicitly cleared.
        sample_offset:
            Sample offset into the audio stream.

            The viewer will seek to this position when the timeline reaches
            this timestamp. For continuous playback, log references at regular
            intervals (e.g., every second).
        duration_samples:
            Optional: Number of samples to play from this offset.

            If not specified, plays until the next reference or end of asset.

        """

        inst = cls.__new__(cls)
        with catch_and_log_exceptions(context=cls.__name__):
            kwargs = {
                "sample_offset": sample_offset,
                "duration_samples": duration_samples,
            }

            if clear_unset:
                kwargs = {k: v if v is not None else [] for k, v in kwargs.items()}  # type: ignore[misc]

            inst.__attrs_init__(**kwargs)
            return inst

        inst.__attrs_clear__()
        return inst

    @classmethod
    def cleared(cls) -> AudioSampleReference:
        """Clear all the fields of a `AudioSampleReference`."""
        return cls.from_fields(clear_unset=True)

    @classmethod
    def columns(
        cls,
        *,
        sample_offset: datatypes.UInt64ArrayLike | None = None,
        duration_samples: datatypes.UInt64ArrayLike | None = None,
    ) -> ComponentColumnList:
        """
        Construct a new column-oriented component bundle.

        This makes it possible to use `rr.send_columns` to send columnar data directly into Rerun.

        The returned columns will be partitioned into unit-length sub-batches by default.
        Use `ComponentColumnList.partition` to repartition the data as needed.

        Parameters
        ----------
        sample_offset:
            Sample offset into the audio stream.

            The viewer will seek to this position when the timeline reaches
            this timestamp. For continuous playback, log references at regular
            intervals (e.g., every second).
        duration_samples:
            Optional: Number of samples to play from this offset.

            If not specified, plays until the next reference or end of asset.

        """

        inst = cls.__new__(cls)
        with catch_and_log_exceptions(context=cls.__name__):
            inst.__attrs_init__(
                sample_offset=sample_offset,
                duration_samples=duration_samples,
            )

        batches = inst.as_component_batches()
        if len(batches) == 0:
            return ComponentColumnList([])

        kwargs = {
            "AudioSampleReference:sample_offset": sample_offset,
            "AudioSampleReference:duration_samples": duration_samples,
        }
        columns = []

        for batch in batches:
            arrow_array = batch.as_arrow_array()

            # For primitive arrays and fixed size list arrays, we infer partition size from the input shape.
            if pa.types.is_primitive(arrow_array.type) or pa.types.is_fixed_size_list(arrow_array.type):
                param = kwargs[batch.component_descriptor().component]  # type: ignore[index]
                shape = np.shape(param)  # type: ignore[arg-type]
                elem_flat_len = int(np.prod(shape[1:])) if len(shape) > 1 else 1  # type: ignore[redundant-expr,misc]

                if pa.types.is_fixed_size_list(arrow_array.type) and arrow_array.type.list_size == elem_flat_len:
                    # If the product of the last dimensions of the shape are equal to the size of the fixed size list array,
                    # we have `num_rows` single element batches (each element is a fixed sized list).
                    # (This should have been already validated by conversion to the arrow_array)
                    batch_length = 1
                else:
                    batch_length = shape[1] if len(shape) > 1 else 1  # type: ignore[redundant-expr,misc]

                num_rows = shape[0] if len(shape) >= 1 else 1  # type: ignore[redundant-expr,misc]
                sizes = batch_length * np.ones(num_rows)
            else:
                # For non-primitive types, default to partitioning each element separately.
                sizes = np.ones(len(arrow_array))

            columns.append(batch.partition(sizes))

        return ComponentColumnList(columns)

    sample_offset: components.SampleOffsetBatch | None = field(
        metadata={"component": True},
        default=None,
        converter=components.SampleOffsetBatch._converter,  # type: ignore[misc]
    )
    # Sample offset into the audio stream.
    #
    # The viewer will seek to this position when the timeline reaches
    # this timestamp. For continuous playback, log references at regular
    # intervals (e.g., every second).
    #
    # (Docstring intentionally commented out to hide this field from the docs)

    duration_samples: components.SampleCountBatch | None = field(
        metadata={"component": True},
        default=None,
        converter=components.SampleCountBatch._converter,  # type: ignore[misc]
    )
    # Optional: Number of samples to play from this offset.
    #
    # If not specified, plays until the next reference or end of asset.
    #
    # (Docstring intentionally commented out to hide this field from the docs)

    __str__ = Archetype.__str__
    __repr__ = Archetype.__repr__  # type: ignore[assignment]
