// DO NOT EDIT! This file was auto-generated by crates/build/re_types_builder/src/codegen/rust/api.rs
// Based on "crates/store/re_sdk_types/definitions/rerun/archetypes/asset_audio.fbs".

#![allow(unused_braces)]
#![allow(unused_imports)]
#![allow(unused_parens)]
#![allow(clippy::allow_attributes)]
#![allow(clippy::clone_on_copy)]
#![allow(clippy::cloned_instead_of_copied)]
#![allow(clippy::map_flatten)]
#![allow(clippy::needless_question_mark)]
#![allow(clippy::new_without_default)]
#![allow(clippy::redundant_closure)]
#![allow(clippy::too_many_arguments)]
#![allow(clippy::too_many_lines)]
#![allow(clippy::wildcard_imports)]

use ::re_types_core::SerializationResult;
use ::re_types_core::try_serialize_field;
use ::re_types_core::{ComponentBatch as _, SerializedComponentBatch};
use ::re_types_core::{ComponentDescriptor, ComponentType};
use ::re_types_core::{DeserializationError, DeserializationResult};

/// **Archetype**: An audio asset containing encoded or raw audio data.
///
/// Store this once (typically as static/timeless data), then use
/// `AudioSampleReference` to reference specific positions on your timeline.
///
/// Similar to how `AssetVideo` + `VideoFrameReference` work for video.
///
/// ## Supported Formats
///
/// - **FLAC**: Lossless, recommended for archival and analysis
/// - **WAV**: Uncompressed PCM in a container
/// - **MP3**: Lossy, widely compatible
/// - **OGG**: Container for Opus or Vorbis codecs
///
/// Codec detection is automatic via Symphonia. The optional metadata fields
/// (`sample_rate`, `channel_layout`, etc.) are hints that can speed up
/// initialization but are not required.
///
/// ⚠️ **This type is _unstable_ and may change significantly in a way that the data won't be backwards compatible.**
///
/// ## Example
///
/// ### Log an audio file
/// ```ignore
/// fn main() -> Result<(), Box<dyn std::error::Error>> {
///     let rec = rerun::RecordingStreamBuilder::new("rerun_example_asset_audio").spawn()?;
///
///     // Log audio asset
///     rec.log_static(
///         "/recording/audio",
///         &rerun::AssetAudio::from_file_path("recording.flac")?,
///     )?;
///
///     Ok(())
/// }
/// ```
#[derive(Clone, Debug, Default)]
pub struct AssetAudio {
    /// The audio data bytes.
    ///
    /// For encoded formats (FLAC, MP3, etc.), this is the raw file/stream bytes.
    /// For raw PCM, this is the sample bytes (use `sample_format` to specify encoding).
    pub blob: Option<SerializedComponentBatch>,

    /// The Media Type of the audio container.
    ///
    /// Supported values:
    /// * `audio/flac`
    /// * `audio/wav`
    /// * `audio/mpeg` (MP3)
    /// * `audio/ogg` (Opus or Vorbis)
    ///
    /// If omitted, the viewer will try to guess from the data blob.
    pub media_type: Option<SerializedComponentBatch>,

    /// Sample rate in Hz (e.g., 48000).
    ///
    /// Matches Symphonia's `SignalSpec.rate`. For encoded formats this can be
    /// read from headers, but providing it enables faster initialization.
    pub sample_rate: Option<SerializedComponentBatch>,

    /// Channel layout as a bitmask.
    ///
    /// Matches Symphonia's `Channels`. Common values:
    /// * `0x3` = Stereo
    /// * `0x3F` = 5.1 Surround
    pub channel_layout: Option<SerializedComponentBatch>,

    /// Bit depth of audio samples (8, 16, 24, or 32).
    ///
    /// Matches Symphonia's `CodecParameters.bits_per_sample`.
    pub bits_per_sample: Option<SerializedComponentBatch>,

    /// Sample format for raw PCM data.
    ///
    /// Only needed when logging raw PCM bytes without a container.
    /// For encoded formats (FLAC, MP3, etc.), this is ignored.
    pub sample_format: Option<SerializedComponentBatch>,
}

impl AssetAudio {
    /// Returns the [`ComponentDescriptor`] for [`Self::blob`].
    ///
    /// The corresponding component is [`crate::components::Blob`].
    #[inline]
    pub fn descriptor_blob() -> ComponentDescriptor {
        ComponentDescriptor {
            archetype: Some("rerun.archetypes.AssetAudio".into()),
            component: "AssetAudio:blob".into(),
            component_type: Some("rerun.components.Blob".into()),
        }
    }

    /// Returns the [`ComponentDescriptor`] for [`Self::media_type`].
    ///
    /// The corresponding component is [`crate::components::MediaType`].
    #[inline]
    pub fn descriptor_media_type() -> ComponentDescriptor {
        ComponentDescriptor {
            archetype: Some("rerun.archetypes.AssetAudio".into()),
            component: "AssetAudio:media_type".into(),
            component_type: Some("rerun.components.MediaType".into()),
        }
    }

    /// Returns the [`ComponentDescriptor`] for [`Self::sample_rate`].
    ///
    /// The corresponding component is [`crate::components::SampleRate`].
    #[inline]
    pub fn descriptor_sample_rate() -> ComponentDescriptor {
        ComponentDescriptor {
            archetype: Some("rerun.archetypes.AssetAudio".into()),
            component: "AssetAudio:sample_rate".into(),
            component_type: Some("rerun.components.SampleRate".into()),
        }
    }

    /// Returns the [`ComponentDescriptor`] for [`Self::channel_layout`].
    ///
    /// The corresponding component is [`crate::components::ChannelLayout`].
    #[inline]
    pub fn descriptor_channel_layout() -> ComponentDescriptor {
        ComponentDescriptor {
            archetype: Some("rerun.archetypes.AssetAudio".into()),
            component: "AssetAudio:channel_layout".into(),
            component_type: Some("rerun.components.ChannelLayout".into()),
        }
    }

    /// Returns the [`ComponentDescriptor`] for [`Self::bits_per_sample`].
    ///
    /// The corresponding component is [`crate::components::BitsPerSample`].
    #[inline]
    pub fn descriptor_bits_per_sample() -> ComponentDescriptor {
        ComponentDescriptor {
            archetype: Some("rerun.archetypes.AssetAudio".into()),
            component: "AssetAudio:bits_per_sample".into(),
            component_type: Some("rerun.components.BitsPerSample".into()),
        }
    }

    /// Returns the [`ComponentDescriptor`] for [`Self::sample_format`].
    ///
    /// The corresponding component is [`crate::components::SampleFormat`].
    #[inline]
    pub fn descriptor_sample_format() -> ComponentDescriptor {
        ComponentDescriptor {
            archetype: Some("rerun.archetypes.AssetAudio".into()),
            component: "AssetAudio:sample_format".into(),
            component_type: Some("rerun.components.SampleFormat".into()),
        }
    }
}

static REQUIRED_COMPONENTS: std::sync::LazyLock<[ComponentDescriptor; 1usize]> =
    std::sync::LazyLock::new(|| [AssetAudio::descriptor_blob()]);

static RECOMMENDED_COMPONENTS: std::sync::LazyLock<[ComponentDescriptor; 1usize]> =
    std::sync::LazyLock::new(|| [AssetAudio::descriptor_media_type()]);

static OPTIONAL_COMPONENTS: std::sync::LazyLock<[ComponentDescriptor; 4usize]> =
    std::sync::LazyLock::new(|| {
        [
            AssetAudio::descriptor_sample_rate(),
            AssetAudio::descriptor_channel_layout(),
            AssetAudio::descriptor_bits_per_sample(),
            AssetAudio::descriptor_sample_format(),
        ]
    });

static ALL_COMPONENTS: std::sync::LazyLock<[ComponentDescriptor; 6usize]> =
    std::sync::LazyLock::new(|| {
        [
            AssetAudio::descriptor_blob(),
            AssetAudio::descriptor_media_type(),
            AssetAudio::descriptor_sample_rate(),
            AssetAudio::descriptor_channel_layout(),
            AssetAudio::descriptor_bits_per_sample(),
            AssetAudio::descriptor_sample_format(),
        ]
    });

impl AssetAudio {
    /// The total number of components in the archetype: 1 required, 1 recommended, 4 optional
    pub const NUM_COMPONENTS: usize = 6usize;
}

impl ::re_types_core::Archetype for AssetAudio {
    #[inline]
    fn name() -> ::re_types_core::ArchetypeName {
        "rerun.archetypes.AssetAudio".into()
    }

    #[inline]
    fn display_name() -> &'static str {
        "Asset audio"
    }

    #[inline]
    fn required_components() -> ::std::borrow::Cow<'static, [ComponentDescriptor]> {
        REQUIRED_COMPONENTS.as_slice().into()
    }

    #[inline]
    fn recommended_components() -> ::std::borrow::Cow<'static, [ComponentDescriptor]> {
        RECOMMENDED_COMPONENTS.as_slice().into()
    }

    #[inline]
    fn optional_components() -> ::std::borrow::Cow<'static, [ComponentDescriptor]> {
        OPTIONAL_COMPONENTS.as_slice().into()
    }

    #[inline]
    fn all_components() -> ::std::borrow::Cow<'static, [ComponentDescriptor]> {
        ALL_COMPONENTS.as_slice().into()
    }

    #[inline]
    fn from_arrow_components(
        arrow_data: impl IntoIterator<Item = (ComponentDescriptor, arrow::array::ArrayRef)>,
    ) -> DeserializationResult<Self> {
        re_tracing::profile_function!();
        use ::re_types_core::{Loggable as _, ResultExt as _};
        let arrays_by_descr: ::nohash_hasher::IntMap<_, _> = arrow_data.into_iter().collect();
        let blob = arrays_by_descr
            .get(&Self::descriptor_blob())
            .map(|array| SerializedComponentBatch::new(array.clone(), Self::descriptor_blob()));
        let media_type = arrays_by_descr
            .get(&Self::descriptor_media_type())
            .map(|array| {
                SerializedComponentBatch::new(array.clone(), Self::descriptor_media_type())
            });
        let sample_rate = arrays_by_descr
            .get(&Self::descriptor_sample_rate())
            .map(|array| {
                SerializedComponentBatch::new(array.clone(), Self::descriptor_sample_rate())
            });
        let channel_layout = arrays_by_descr
            .get(&Self::descriptor_channel_layout())
            .map(|array| {
                SerializedComponentBatch::new(array.clone(), Self::descriptor_channel_layout())
            });
        let bits_per_sample = arrays_by_descr
            .get(&Self::descriptor_bits_per_sample())
            .map(|array| {
                SerializedComponentBatch::new(array.clone(), Self::descriptor_bits_per_sample())
            });
        let sample_format = arrays_by_descr
            .get(&Self::descriptor_sample_format())
            .map(|array| {
                SerializedComponentBatch::new(array.clone(), Self::descriptor_sample_format())
            });
        Ok(Self {
            blob,
            media_type,
            sample_rate,
            channel_layout,
            bits_per_sample,
            sample_format,
        })
    }
}

impl ::re_types_core::AsComponents for AssetAudio {
    #[inline]
    fn as_serialized_batches(&self) -> Vec<SerializedComponentBatch> {
        use ::re_types_core::Archetype as _;
        [
            self.blob.clone(),
            self.media_type.clone(),
            self.sample_rate.clone(),
            self.channel_layout.clone(),
            self.bits_per_sample.clone(),
            self.sample_format.clone(),
        ]
        .into_iter()
        .flatten()
        .collect()
    }
}

impl ::re_types_core::ArchetypeReflectionMarker for AssetAudio {}

impl AssetAudio {
    /// Create a new `AssetAudio`.
    #[inline]
    pub fn new(blob: impl Into<crate::components::Blob>) -> Self {
        Self {
            blob: try_serialize_field(Self::descriptor_blob(), [blob]),
            media_type: None,
            sample_rate: None,
            channel_layout: None,
            bits_per_sample: None,
            sample_format: None,
        }
    }

    /// Update only some specific fields of a `AssetAudio`.
    #[inline]
    pub fn update_fields() -> Self {
        Self::default()
    }

    /// Clear all the fields of a `AssetAudio`.
    #[inline]
    pub fn clear_fields() -> Self {
        use ::re_types_core::Loggable as _;
        Self {
            blob: Some(SerializedComponentBatch::new(
                crate::components::Blob::arrow_empty(),
                Self::descriptor_blob(),
            )),
            media_type: Some(SerializedComponentBatch::new(
                crate::components::MediaType::arrow_empty(),
                Self::descriptor_media_type(),
            )),
            sample_rate: Some(SerializedComponentBatch::new(
                crate::components::SampleRate::arrow_empty(),
                Self::descriptor_sample_rate(),
            )),
            channel_layout: Some(SerializedComponentBatch::new(
                crate::components::ChannelLayout::arrow_empty(),
                Self::descriptor_channel_layout(),
            )),
            bits_per_sample: Some(SerializedComponentBatch::new(
                crate::components::BitsPerSample::arrow_empty(),
                Self::descriptor_bits_per_sample(),
            )),
            sample_format: Some(SerializedComponentBatch::new(
                crate::components::SampleFormat::arrow_empty(),
                Self::descriptor_sample_format(),
            )),
        }
    }

    /// Partitions the component data into multiple sub-batches.
    ///
    /// Specifically, this transforms the existing [`SerializedComponentBatch`]es data into [`SerializedComponentColumn`]s
    /// instead, via [`SerializedComponentBatch::partitioned`].
    ///
    /// This makes it possible to use `RecordingStream::send_columns` to send columnar data directly into Rerun.
    ///
    /// The specified `lengths` must sum to the total length of the component batch.
    ///
    /// [`SerializedComponentColumn`]: [::re_types_core::SerializedComponentColumn]
    #[inline]
    pub fn columns<I>(
        self,
        _lengths: I,
    ) -> SerializationResult<impl Iterator<Item = ::re_types_core::SerializedComponentColumn>>
    where
        I: IntoIterator<Item = usize> + Clone,
    {
        let columns = [
            self.blob
                .map(|blob| blob.partitioned(_lengths.clone()))
                .transpose()?,
            self.media_type
                .map(|media_type| media_type.partitioned(_lengths.clone()))
                .transpose()?,
            self.sample_rate
                .map(|sample_rate| sample_rate.partitioned(_lengths.clone()))
                .transpose()?,
            self.channel_layout
                .map(|channel_layout| channel_layout.partitioned(_lengths.clone()))
                .transpose()?,
            self.bits_per_sample
                .map(|bits_per_sample| bits_per_sample.partitioned(_lengths.clone()))
                .transpose()?,
            self.sample_format
                .map(|sample_format| sample_format.partitioned(_lengths.clone()))
                .transpose()?,
        ];
        Ok(columns.into_iter().flatten())
    }

    /// Helper to partition the component data into unit-length sub-batches.
    ///
    /// This is semantically similar to calling [`Self::columns`] with `std::iter::take(1).repeat(n)`,
    /// where `n` is automatically guessed.
    #[inline]
    pub fn columns_of_unit_batches(
        self,
    ) -> SerializationResult<impl Iterator<Item = ::re_types_core::SerializedComponentColumn>> {
        let len_blob = self.blob.as_ref().map(|b| b.array.len());
        let len_media_type = self.media_type.as_ref().map(|b| b.array.len());
        let len_sample_rate = self.sample_rate.as_ref().map(|b| b.array.len());
        let len_channel_layout = self.channel_layout.as_ref().map(|b| b.array.len());
        let len_bits_per_sample = self.bits_per_sample.as_ref().map(|b| b.array.len());
        let len_sample_format = self.sample_format.as_ref().map(|b| b.array.len());
        let len = None
            .or(len_blob)
            .or(len_media_type)
            .or(len_sample_rate)
            .or(len_channel_layout)
            .or(len_bits_per_sample)
            .or(len_sample_format)
            .unwrap_or(0);
        self.columns(std::iter::repeat_n(1, len))
    }

    /// The audio data bytes.
    ///
    /// For encoded formats (FLAC, MP3, etc.), this is the raw file/stream bytes.
    /// For raw PCM, this is the sample bytes (use `sample_format` to specify encoding).
    #[inline]
    pub fn with_blob(mut self, blob: impl Into<crate::components::Blob>) -> Self {
        self.blob = try_serialize_field(Self::descriptor_blob(), [blob]);
        self
    }

    /// This method makes it possible to pack multiple [`crate::components::Blob`] in a single component batch.
    ///
    /// This only makes sense when used in conjunction with [`Self::columns`]. [`Self::with_blob`] should
    /// be used when logging a single row's worth of data.
    #[inline]
    pub fn with_many_blob(
        mut self,
        blob: impl IntoIterator<Item = impl Into<crate::components::Blob>>,
    ) -> Self {
        self.blob = try_serialize_field(Self::descriptor_blob(), blob);
        self
    }

    /// The Media Type of the audio container.
    ///
    /// Supported values:
    /// * `audio/flac`
    /// * `audio/wav`
    /// * `audio/mpeg` (MP3)
    /// * `audio/ogg` (Opus or Vorbis)
    ///
    /// If omitted, the viewer will try to guess from the data blob.
    #[inline]
    pub fn with_media_type(mut self, media_type: impl Into<crate::components::MediaType>) -> Self {
        self.media_type = try_serialize_field(Self::descriptor_media_type(), [media_type]);
        self
    }

    /// This method makes it possible to pack multiple [`crate::components::MediaType`] in a single component batch.
    ///
    /// This only makes sense when used in conjunction with [`Self::columns`]. [`Self::with_media_type`] should
    /// be used when logging a single row's worth of data.
    #[inline]
    pub fn with_many_media_type(
        mut self,
        media_type: impl IntoIterator<Item = impl Into<crate::components::MediaType>>,
    ) -> Self {
        self.media_type = try_serialize_field(Self::descriptor_media_type(), media_type);
        self
    }

    /// Sample rate in Hz (e.g., 48000).
    ///
    /// Matches Symphonia's `SignalSpec.rate`. For encoded formats this can be
    /// read from headers, but providing it enables faster initialization.
    #[inline]
    pub fn with_sample_rate(
        mut self,
        sample_rate: impl Into<crate::components::SampleRate>,
    ) -> Self {
        self.sample_rate = try_serialize_field(Self::descriptor_sample_rate(), [sample_rate]);
        self
    }

    /// This method makes it possible to pack multiple [`crate::components::SampleRate`] in a single component batch.
    ///
    /// This only makes sense when used in conjunction with [`Self::columns`]. [`Self::with_sample_rate`] should
    /// be used when logging a single row's worth of data.
    #[inline]
    pub fn with_many_sample_rate(
        mut self,
        sample_rate: impl IntoIterator<Item = impl Into<crate::components::SampleRate>>,
    ) -> Self {
        self.sample_rate = try_serialize_field(Self::descriptor_sample_rate(), sample_rate);
        self
    }

    /// Channel layout as a bitmask.
    ///
    /// Matches Symphonia's `Channels`. Common values:
    /// * `0x3` = Stereo
    /// * `0x3F` = 5.1 Surround
    #[inline]
    pub fn with_channel_layout(
        mut self,
        channel_layout: impl Into<crate::components::ChannelLayout>,
    ) -> Self {
        self.channel_layout =
            try_serialize_field(Self::descriptor_channel_layout(), [channel_layout]);
        self
    }

    /// This method makes it possible to pack multiple [`crate::components::ChannelLayout`] in a single component batch.
    ///
    /// This only makes sense when used in conjunction with [`Self::columns`]. [`Self::with_channel_layout`] should
    /// be used when logging a single row's worth of data.
    #[inline]
    pub fn with_many_channel_layout(
        mut self,
        channel_layout: impl IntoIterator<Item = impl Into<crate::components::ChannelLayout>>,
    ) -> Self {
        self.channel_layout =
            try_serialize_field(Self::descriptor_channel_layout(), channel_layout);
        self
    }

    /// Bit depth of audio samples (8, 16, 24, or 32).
    ///
    /// Matches Symphonia's `CodecParameters.bits_per_sample`.
    #[inline]
    pub fn with_bits_per_sample(
        mut self,
        bits_per_sample: impl Into<crate::components::BitsPerSample>,
    ) -> Self {
        self.bits_per_sample =
            try_serialize_field(Self::descriptor_bits_per_sample(), [bits_per_sample]);
        self
    }

    /// This method makes it possible to pack multiple [`crate::components::BitsPerSample`] in a single component batch.
    ///
    /// This only makes sense when used in conjunction with [`Self::columns`]. [`Self::with_bits_per_sample`] should
    /// be used when logging a single row's worth of data.
    #[inline]
    pub fn with_many_bits_per_sample(
        mut self,
        bits_per_sample: impl IntoIterator<Item = impl Into<crate::components::BitsPerSample>>,
    ) -> Self {
        self.bits_per_sample =
            try_serialize_field(Self::descriptor_bits_per_sample(), bits_per_sample);
        self
    }

    /// Sample format for raw PCM data.
    ///
    /// Only needed when logging raw PCM bytes without a container.
    /// For encoded formats (FLAC, MP3, etc.), this is ignored.
    #[inline]
    pub fn with_sample_format(
        mut self,
        sample_format: impl Into<crate::components::SampleFormat>,
    ) -> Self {
        self.sample_format = try_serialize_field(Self::descriptor_sample_format(), [sample_format]);
        self
    }

    /// This method makes it possible to pack multiple [`crate::components::SampleFormat`] in a single component batch.
    ///
    /// This only makes sense when used in conjunction with [`Self::columns`]. [`Self::with_sample_format`] should
    /// be used when logging a single row's worth of data.
    #[inline]
    pub fn with_many_sample_format(
        mut self,
        sample_format: impl IntoIterator<Item = impl Into<crate::components::SampleFormat>>,
    ) -> Self {
        self.sample_format = try_serialize_field(Self::descriptor_sample_format(), sample_format);
        self
    }
}

impl ::re_byte_size::SizeBytes for AssetAudio {
    #[inline]
    fn heap_size_bytes(&self) -> u64 {
        self.blob.heap_size_bytes()
            + self.media_type.heap_size_bytes()
            + self.sample_rate.heap_size_bytes()
            + self.channel_layout.heap_size_bytes()
            + self.bits_per_sample.heap_size_bytes()
            + self.sample_format.heap_size_bytes()
    }
}
