// DO NOT EDIT! This file was auto-generated by crates/build/re_types_builder/src/codegen/rust/api.rs
// Based on "crates/store/re_sdk_types/definitions/rerun/archetypes/audio_sample_reference.fbs".

#![allow(unused_braces)]
#![allow(unused_imports)]
#![allow(unused_parens)]
#![allow(clippy::allow_attributes)]
#![allow(clippy::clone_on_copy)]
#![allow(clippy::cloned_instead_of_copied)]
#![allow(clippy::map_flatten)]
#![allow(clippy::needless_question_mark)]
#![allow(clippy::new_without_default)]
#![allow(clippy::redundant_closure)]
#![allow(clippy::too_many_arguments)]
#![allow(clippy::too_many_lines)]
#![allow(clippy::wildcard_imports)]

use ::re_types_core::SerializationResult;
use ::re_types_core::try_serialize_field;
use ::re_types_core::{ComponentBatch as _, SerializedComponentBatch};
use ::re_types_core::{ComponentDescriptor, ComponentType};
use ::re_types_core::{DeserializationError, DeserializationResult};

/// **Archetype**: Reference to a position within an `AssetAudio`.
///
/// Used to place audio on the timeline and enable synchronized playback
/// with other data streams (video, sensors, detections).
///
/// Log these at timestamps where you want the audio to be "active" on the timeline.
/// The viewer will decode and play from the specified sample offset.
///
/// ⚠️ **This type is _unstable_ and may change significantly in a way that the data won't be backwards compatible.**
///
/// ## Example
///
/// ### Reference audio frames on timeline
/// ```ignore
/// fn main() -> Result<(), Box<dyn std::error::Error>> {
///     let rec = rerun::RecordingStreamBuilder::new("rerun_example_audio_sample_reference").spawn()?;
///
///     // Log audio asset first
///     rec.log_static(
///         "/recording/audio",
///         &rerun::AssetAudio::from_file_path("recording.flac")?,
///     )?;
///
///     // Log timeline references
///     let sample_rate: u64 = 48000;
///     for t in 0..60 {
///         rec.set_time_seconds("audio_time", t as f64);
///         rec.log(
///             "/recording/audio",
///             &rerun::AudioSampleReference::new(t * sample_rate),
///         )?;
///     }
///
///     Ok(())
/// }
/// ```
#[derive(Clone, Debug, Default)]
pub struct AudioSampleReference {
    /// Sample offset into the audio stream.
    ///
    /// The viewer will seek to this position when the timeline reaches
    /// this timestamp. For continuous playback, log references at regular
    /// intervals (e.g., every second).
    pub sample_offset: Option<SerializedComponentBatch>,

    /// Optional: Number of samples to play from this offset.
    ///
    /// If not specified, plays until the next reference or end of asset.
    pub duration_samples: Option<SerializedComponentBatch>,
}

impl AudioSampleReference {
    /// Returns the [`ComponentDescriptor`] for [`Self::sample_offset`].
    ///
    /// The corresponding component is [`crate::components::SampleOffset`].
    #[inline]
    pub fn descriptor_sample_offset() -> ComponentDescriptor {
        ComponentDescriptor {
            archetype: Some("rerun.archetypes.AudioSampleReference".into()),
            component: "AudioSampleReference:sample_offset".into(),
            component_type: Some("rerun.components.SampleOffset".into()),
        }
    }

    /// Returns the [`ComponentDescriptor`] for [`Self::duration_samples`].
    ///
    /// The corresponding component is [`crate::components::SampleCount`].
    #[inline]
    pub fn descriptor_duration_samples() -> ComponentDescriptor {
        ComponentDescriptor {
            archetype: Some("rerun.archetypes.AudioSampleReference".into()),
            component: "AudioSampleReference:duration_samples".into(),
            component_type: Some("rerun.components.SampleCount".into()),
        }
    }
}

static REQUIRED_COMPONENTS: std::sync::LazyLock<[ComponentDescriptor; 1usize]> =
    std::sync::LazyLock::new(|| [AudioSampleReference::descriptor_sample_offset()]);

static RECOMMENDED_COMPONENTS: std::sync::LazyLock<[ComponentDescriptor; 0usize]> =
    std::sync::LazyLock::new(|| []);

static OPTIONAL_COMPONENTS: std::sync::LazyLock<[ComponentDescriptor; 1usize]> =
    std::sync::LazyLock::new(|| [AudioSampleReference::descriptor_duration_samples()]);

static ALL_COMPONENTS: std::sync::LazyLock<[ComponentDescriptor; 2usize]> =
    std::sync::LazyLock::new(|| {
        [
            AudioSampleReference::descriptor_sample_offset(),
            AudioSampleReference::descriptor_duration_samples(),
        ]
    });

impl AudioSampleReference {
    /// The total number of components in the archetype: 1 required, 0 recommended, 1 optional
    pub const NUM_COMPONENTS: usize = 2usize;
}

impl ::re_types_core::Archetype for AudioSampleReference {
    #[inline]
    fn name() -> ::re_types_core::ArchetypeName {
        "rerun.archetypes.AudioSampleReference".into()
    }

    #[inline]
    fn display_name() -> &'static str {
        "Audio sample reference"
    }

    #[inline]
    fn required_components() -> ::std::borrow::Cow<'static, [ComponentDescriptor]> {
        REQUIRED_COMPONENTS.as_slice().into()
    }

    #[inline]
    fn recommended_components() -> ::std::borrow::Cow<'static, [ComponentDescriptor]> {
        RECOMMENDED_COMPONENTS.as_slice().into()
    }

    #[inline]
    fn optional_components() -> ::std::borrow::Cow<'static, [ComponentDescriptor]> {
        OPTIONAL_COMPONENTS.as_slice().into()
    }

    #[inline]
    fn all_components() -> ::std::borrow::Cow<'static, [ComponentDescriptor]> {
        ALL_COMPONENTS.as_slice().into()
    }

    #[inline]
    fn from_arrow_components(
        arrow_data: impl IntoIterator<Item = (ComponentDescriptor, arrow::array::ArrayRef)>,
    ) -> DeserializationResult<Self> {
        re_tracing::profile_function!();
        use ::re_types_core::{Loggable as _, ResultExt as _};
        let arrays_by_descr: ::nohash_hasher::IntMap<_, _> = arrow_data.into_iter().collect();
        let sample_offset = arrays_by_descr
            .get(&Self::descriptor_sample_offset())
            .map(|array| {
                SerializedComponentBatch::new(array.clone(), Self::descriptor_sample_offset())
            });
        let duration_samples = arrays_by_descr
            .get(&Self::descriptor_duration_samples())
            .map(|array| {
                SerializedComponentBatch::new(array.clone(), Self::descriptor_duration_samples())
            });
        Ok(Self {
            sample_offset,
            duration_samples,
        })
    }
}

impl ::re_types_core::AsComponents for AudioSampleReference {
    #[inline]
    fn as_serialized_batches(&self) -> Vec<SerializedComponentBatch> {
        use ::re_types_core::Archetype as _;
        [self.sample_offset.clone(), self.duration_samples.clone()]
            .into_iter()
            .flatten()
            .collect()
    }
}

impl ::re_types_core::ArchetypeReflectionMarker for AudioSampleReference {}

impl AudioSampleReference {
    /// Create a new `AudioSampleReference`.
    #[inline]
    pub fn new(sample_offset: impl Into<crate::components::SampleOffset>) -> Self {
        Self {
            sample_offset: try_serialize_field(Self::descriptor_sample_offset(), [sample_offset]),
            duration_samples: None,
        }
    }

    /// Update only some specific fields of a `AudioSampleReference`.
    #[inline]
    pub fn update_fields() -> Self {
        Self::default()
    }

    /// Clear all the fields of a `AudioSampleReference`.
    #[inline]
    pub fn clear_fields() -> Self {
        use ::re_types_core::Loggable as _;
        Self {
            sample_offset: Some(SerializedComponentBatch::new(
                crate::components::SampleOffset::arrow_empty(),
                Self::descriptor_sample_offset(),
            )),
            duration_samples: Some(SerializedComponentBatch::new(
                crate::components::SampleCount::arrow_empty(),
                Self::descriptor_duration_samples(),
            )),
        }
    }

    /// Partitions the component data into multiple sub-batches.
    ///
    /// Specifically, this transforms the existing [`SerializedComponentBatch`]es data into [`SerializedComponentColumn`]s
    /// instead, via [`SerializedComponentBatch::partitioned`].
    ///
    /// This makes it possible to use `RecordingStream::send_columns` to send columnar data directly into Rerun.
    ///
    /// The specified `lengths` must sum to the total length of the component batch.
    ///
    /// [`SerializedComponentColumn`]: [::re_types_core::SerializedComponentColumn]
    #[inline]
    pub fn columns<I>(
        self,
        _lengths: I,
    ) -> SerializationResult<impl Iterator<Item = ::re_types_core::SerializedComponentColumn>>
    where
        I: IntoIterator<Item = usize> + Clone,
    {
        let columns = [
            self.sample_offset
                .map(|sample_offset| sample_offset.partitioned(_lengths.clone()))
                .transpose()?,
            self.duration_samples
                .map(|duration_samples| duration_samples.partitioned(_lengths.clone()))
                .transpose()?,
        ];
        Ok(columns.into_iter().flatten())
    }

    /// Helper to partition the component data into unit-length sub-batches.
    ///
    /// This is semantically similar to calling [`Self::columns`] with `std::iter::take(1).repeat(n)`,
    /// where `n` is automatically guessed.
    #[inline]
    pub fn columns_of_unit_batches(
        self,
    ) -> SerializationResult<impl Iterator<Item = ::re_types_core::SerializedComponentColumn>> {
        let len_sample_offset = self.sample_offset.as_ref().map(|b| b.array.len());
        let len_duration_samples = self.duration_samples.as_ref().map(|b| b.array.len());
        let len = None
            .or(len_sample_offset)
            .or(len_duration_samples)
            .unwrap_or(0);
        self.columns(std::iter::repeat_n(1, len))
    }

    /// Sample offset into the audio stream.
    ///
    /// The viewer will seek to this position when the timeline reaches
    /// this timestamp. For continuous playback, log references at regular
    /// intervals (e.g., every second).
    #[inline]
    pub fn with_sample_offset(
        mut self,
        sample_offset: impl Into<crate::components::SampleOffset>,
    ) -> Self {
        self.sample_offset = try_serialize_field(Self::descriptor_sample_offset(), [sample_offset]);
        self
    }

    /// This method makes it possible to pack multiple [`crate::components::SampleOffset`] in a single component batch.
    ///
    /// This only makes sense when used in conjunction with [`Self::columns`]. [`Self::with_sample_offset`] should
    /// be used when logging a single row's worth of data.
    #[inline]
    pub fn with_many_sample_offset(
        mut self,
        sample_offset: impl IntoIterator<Item = impl Into<crate::components::SampleOffset>>,
    ) -> Self {
        self.sample_offset = try_serialize_field(Self::descriptor_sample_offset(), sample_offset);
        self
    }

    /// Optional: Number of samples to play from this offset.
    ///
    /// If not specified, plays until the next reference or end of asset.
    #[inline]
    pub fn with_duration_samples(
        mut self,
        duration_samples: impl Into<crate::components::SampleCount>,
    ) -> Self {
        self.duration_samples =
            try_serialize_field(Self::descriptor_duration_samples(), [duration_samples]);
        self
    }

    /// This method makes it possible to pack multiple [`crate::components::SampleCount`] in a single component batch.
    ///
    /// This only makes sense when used in conjunction with [`Self::columns`]. [`Self::with_duration_samples`] should
    /// be used when logging a single row's worth of data.
    #[inline]
    pub fn with_many_duration_samples(
        mut self,
        duration_samples: impl IntoIterator<Item = impl Into<crate::components::SampleCount>>,
    ) -> Self {
        self.duration_samples =
            try_serialize_field(Self::descriptor_duration_samples(), duration_samples);
        self
    }
}

impl ::re_byte_size::SizeBytes for AudioSampleReference {
    #[inline]
    fn heap_size_bytes(&self) -> u64 {
        self.sample_offset.heap_size_bytes() + self.duration_samples.heap_size_bytes()
    }
}
