// DO NOT EDIT! This file was auto-generated by crates/build/re_types_builder/src/codegen/cpp/mod.rs
// Based on "crates/store/re_sdk_types/definitions/rerun/datatypes/sample_format.fbs".

#pragma once

#include "../result.hpp"

#include <cstdint>
#include <memory>

namespace arrow {
    /// \private
    template <typename T>
    class NumericBuilder;

    class Array;
    class DataType;
    class UInt8Type;
    using UInt8Builder = NumericBuilder<UInt8Type>;
} // namespace arrow

namespace rerun::datatypes {
    /// **Datatype**: Audio sample format.
    ///
    /// Matches Symphonia's `SampleFormat` enum. Describes how decoded audio
    /// samples are represented in memory.
    enum class SampleFormat : uint8_t {

        /// Unsigned 8-bit integer.
        U8 = 1,

        /// Unsigned 16-bit integer.
        U16 = 2,

        /// Unsigned 24-bit integer (stored in 32 bits).
        U24 = 3,

        /// Unsigned 32-bit integer.
        U32 = 4,

        /// Signed 8-bit integer.
        S8 = 5,

        /// Signed 16-bit integer (CD quality).
        S16 = 6,

        /// Signed 24-bit integer (professional audio).
        S24 = 7,

        /// Signed 32-bit integer.
        S32 = 8,

        /// 32-bit IEEE-754 floating point.
        F32 = 9,

        /// 64-bit IEEE-754 floating point.
        F64 = 10,
    };
} // namespace rerun::datatypes

namespace rerun {
    template <typename T>
    struct Loggable;

    /// \private
    template <>
    struct Loggable<datatypes::SampleFormat> {
        static constexpr std::string_view ComponentType = "rerun.datatypes.SampleFormat";

        /// Returns the arrow data type this type corresponds to.
        static const std::shared_ptr<arrow::DataType>& arrow_datatype();

        /// Serializes an array of `rerun::datatypes::SampleFormat` into an arrow array.
        static Result<std::shared_ptr<arrow::Array>> to_arrow(
            const datatypes::SampleFormat* instances, size_t num_instances
        );

        /// Fills an arrow array builder with an array of this type.
        static rerun::Error fill_arrow_array_builder(
            arrow::UInt8Builder* builder, const datatypes::SampleFormat* elements,
            size_t num_elements
        );
    };
} // namespace rerun
